import HartshorneLib.Basic
import HartshorneLib.Chapter1
import HartshorneLib.Chapter1Topology
import HartshorneLib.Chapter1Ideals
import HartshorneLib.Chapter1Variety
import HartshorneLib.Chapter1CoordinateRing
import HartshorneLib.Chapter1Closure
import HartshorneLib.Chapter1Coordinates
import HartshorneLib.Chapter1Prime
import HartshorneLib.Chapter1Correspondence
import HartshorneLib.Chapter1QuasiAffine
import HartshorneLib.Chapter1Spectrum
import HartshorneLib.Chapter1Curves
import HartshorneLib.Chapter1CurveStalks
import HartshorneLib.Chapter4Curves
import HartshorneLib.Chapter4DivisorInduction
import HartshorneLib.Chapter4DivisorSupport
import HartshorneLib.Chapter4Effective
import HartshorneLib.Chapter4PrincipalDivisors
import HartshorneLib.Chapter4OrderComparison
import HartshorneLib.Chapter4PrincipalDivisorDegree
import HartshorneLib.Chapter4DivisorClass
import HartshorneLib.Chapter4DegreeClass
import HartshorneLib.Chapter4EffectiveRepresentative
import HartshorneLib.Chapter4LinearSystems
import HartshorneLib.Chapter2
import HartshorneLib.Chapter2Sheaves
import HartshorneLib.Chapter2LineBundles
import HartshorneLib.Chapter2ModuleKSheaf
import HartshorneLib.Chapter2Cohomology
import HartshorneLib.Chapter2Chi
import HartshorneLib.Chapter2ChiSlice
import HartshorneLib.Chapter4DivisorSheaf
import HartshorneLib.Chapter4DivisorSheafZero
import HartshorneLib.Chapter4ChiBase
import HartshorneLib.Chapter4Skyscraper
import HartshorneLib.Chapter4ResidueDegree
import HartshorneLib.Chapter4WeightedDegree

/-!
# HartshorneLib

Lean formalization library for the source-faithful blueprint at this project root.
-/
