/-
Copyright (c) 2026 The StacksPart05Lib authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The StacksPart05Lib Contributors
-/

import Mathlib.Logic.Relation

/-!
# StacksPart05Lib.Groupoids

The invariant-map factorization property for a quotient, in the elementary
set-theoretic form underlying Stacks, Tag 048F.
-/

namespace StacksPart05Lib

/-- A map is invariant for a setoid when it is constant on related points. -/
def Invariant {U X : Type _} (r : Setoid U) (φ : U → X) : Prop :=
  ∀ ⦃a b : U⦄, r.r a b → φ a = φ b

/-- An invariant map factors through the quotient by the relation. -/
theorem invariant_iff_factors_through_quotient {U X : Type _} (r : Setoid U)
    (φ : U → X) :
    Invariant r φ ↔ ∃ ψ : Quotient r → X, ψ ∘ Quotient.mk r = φ := by
  constructor
  · intro h
    refine ⟨Quotient.lift φ (fun a b hab => h hab), ?_⟩
    funext a
    rfl
  · rintro ⟨ψ, hψ⟩ a b hab
    rw [← hψ]
    exact congrArg ψ (Quotient.sound hab)

/-- The orbit generated by a (possibly non-symmetric) relation. -/
def orbit {U : Type _} (ρ : U → U → Prop) (u : U) : Set U :=
  {v | Relation.EqvGen ρ u v}

/-- A map constant on the generating relation is constant on every orbit.

This is the set-theoretic core of the orbit lemma for quotient groupoids. -/
theorem invariant_map_constant_on_orbit {U X : Type _} {ρ : U → U → Prop}
    (φ : U → X) (hφ : ∀ ⦃a b : U⦄, ρ a b → φ a = φ b)
    {u v : U} (hv : v ∈ orbit ρ u) : φ u = φ v := by
  induction hv with
  | rel a b hab => exact hφ hab
  | refl a => rfl
  | symm a b hab ih => exact ih.symm
  | trans a b c hab hbc ih₁ ih₂ => exact ih₁.trans ih₂

/-- For an equivalence relation, the generated orbit is the original relation. -/
theorem mem_orbit_iff {U : Type _} {ρ : U → U → Prop} (hρ : Equivalence ρ)
    {u v : U} : v ∈ orbit ρ u ↔ ρ u v := by
  exact hρ.eqvGen_iff

/-- Quotient factorization for a map invariant under an arbitrary relation. -/
theorem relation_invariant_iff_factors_through_quotient {U X : Type _}
    (ρ : U → U → Prop) (φ : U → X) :
    (∀ ⦃a b : U⦄, ρ a b → φ a = φ b) ↔
      ∃ ψ : Quotient (Relation.EqvGen.setoid ρ) → X,
        ψ ∘ Quotient.mk (Relation.EqvGen.setoid ρ) = φ := by
  constructor
  · intro h
    apply (invariant_iff_factors_through_quotient
      (Relation.EqvGen.setoid ρ) φ).1
    intro a b hab
    exact invariant_map_constant_on_orbit φ h hab
  · rintro ⟨ψ, hψ⟩ a b hab
    rw [← hψ]
    exact congrArg ψ (Quotient.sound (Relation.EqvGen.rel a b hab))

end StacksPart05Lib
