/-
Copyright (c) 2026 The StacksPart01Lib authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The StacksPart01Lib Contributors
-/

import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.RingTheory.Artinian.Module
import Mathlib.RingTheory.Ideal.Maps

/-!
# StacksPart01Lib.CommutativeAlgebra

Small, source-faithful consequences of the commutative-algebra preliminaries.
-/

namespace StacksPart01

open Polynomial

/-- The Cayley--Hamilton identity for matrices (Stacks, Tag 00DX). -/
theorem charpoly {R n : Type*} [CommRing R] [Fintype n] [DecidableEq n]
    (A : Matrix n n R) : aeval A A.charpoly = 0 := by
  exact Matrix.aeval_self_charpoly A

/-- Finite modules over a Noetherian ring have finite presentations, finite
submodules, and the Noetherian module property (Stacks, Tag 00IK). -/
theorem noetherian_basic {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    [IsNoetherianRing R] [Module.Finite R M] :
    Module.FinitePresentation R M ∧
      (∀ N : Submodule R M, Module.Finite R N) ∧
      IsNoetherian R M := by
  refine ⟨Module.finitePresentation_of_finite R M, ?_, inferInstance⟩
  intro N
  exact Module.Finite.of_fg (Submodule.FG.of_le Module.Finite.fg_top le_top)

/-- An Artinian ring has finitely many maximal ideals (Stacks, Tag 00J7). -/
theorem artinian_finite_maximal_ideals {R : Type*} [CommSemiring R]
    [IsArtinianRing R] : {I : Ideal R | I.IsMaximal}.Finite := by
  exact IsArtinianRing.setOf_isMaximal_finite R

/-! ### Maximal minors and matrix left inverses

The Stacks Project indexes the maximal minors of a rectangular matrix by
subsets of its rows.  An injective row map is a convenient Lean encoding of
such a choice (different enumerations generate the same ideal up to signs).
-/

/-- The matrix selecting the rows in an injection `e : \kappa ↪ \ι`. -/
noncomputable def rowProjection {R ι κ : Type*} [Zero R] [One R]
    [DecidableEq ι] (e : κ ↪ ι) : Matrix κ ι R :=
  Matrix.of fun i j => if e i = j then 1 else 0

lemma rowProjection_mul {R ι κ : Type*} [CommRing R]
    [Fintype ι] [DecidableEq ι] (A : Matrix ι κ R) (e : κ ↪ ι) :
    rowProjection e * A = A.submatrix e id := by
  classical
  ext i k
  simp only [Matrix.mul_apply, rowProjection, Matrix.of_apply, Matrix.submatrix_apply,
    id_eq]
  rw [Fintype.sum_eq_single (e i)]
  · simp
  · intro b hbe
    simp [Ne.symm hbe]

/-- The ideal generated by all maximal (row) minors of a rectangular matrix.

The use of row injections avoids choosing an ordering on the finite row type;
reindexing a chosen subset changes a determinant only by a unit sign.
-/
noncomputable def minorIdeal {R ι κ : Type*} [CommRing R]
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (A : Matrix ι κ R) : Ideal R :=
  Ideal.span (Set.range fun e : κ ↪ ι => (A.submatrix e id).det)

/-- Every element of the maximal-minor ideal gives a matrix left inverse.

This is part (1) of Stacks, Lemma 07DQ. -/
theorem matrix_left_inverse_of_mem_minorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R) {f : R}
    (hf : f ∈ minorIdeal A) :
    ∃ B : Matrix κ ι R, B * A = f • (1 : Matrix κ κ R) := by
  classical
  change f ∈ Submodule.span R
    (Set.range fun e : κ ↪ ι => (A.submatrix e id).det) at hf
  refine Submodule.span_induction (p := fun f _ => ∃ B : Matrix κ ι R,
      B * A = f • (1 : Matrix κ κ R)) ?gen ?zero ?add ?smul hf
  · intro f hf
    rcases hf with ⟨e, rfl⟩
    refine ⟨Matrix.adjugate (A.submatrix e id) * rowProjection e, ?_⟩
    rw [Matrix.mul_assoc, rowProjection_mul, Matrix.adjugate_mul]
  · refine ⟨0, ?_⟩
    simp
  · intro x y hx hy ⟨Bx, hBx⟩ ⟨By, hBy⟩
    refine ⟨Bx + By, ?_⟩
    rw [Matrix.add_mul, hBx, hBy, add_smul]
  · intro a x hx ⟨Bx, hBx⟩
    refine ⟨a • Bx, ?_⟩
    rw [Matrix.smul_mul, hBx, smul_smul]
    rfl

/-! The converse in 07DQ is the Cauchy--Binet direction.  The rank-one case
is useful on its own and is completely elementary, so we expose it without
introducing a second rectangular-determinant infrastructure layer. -/

/-- For a one-column matrix, a left inverse forces its scalar into the ideal
generated by the entries (the `m = 1` case of 07DQ(2)). -/
theorem matrix_left_inverse_one_mem_minorIdeal
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (A : Matrix ι (Fin 1) R) {f : R} (B : Matrix (Fin 1) ι R)
    (hBA : B * A = f • (1 : Matrix (Fin 1) (Fin 1) R)) :
    f ∈ minorIdeal A := by
  classical
  change f ∈ Submodule.span R
    (Set.range fun e : (Fin 1) ↪ ι => (A.submatrix e id).det)
  have hentry : f = ∑ i : ι, B 0 i * A i 0 := by
    have h := congrArg (fun M : Matrix (Fin 1) (Fin 1) R => M 0 0) hBA
    simpa [Matrix.mul_apply, Matrix.one_apply] using h.symm
  rw [hentry]
  -- Each one-by-one row minor is exactly the corresponding entry of `A`.
  refine Submodule.sum_mem (minorIdeal A) (t := Finset.univ) ?_
  intro i hi
  apply Submodule.smul_mem _ (B 0 i)
  change A i 0 ∈ Submodule.span R
    (Set.range fun e : (Fin 1) ↪ ι => (A.submatrix e id).det)
  apply Submodule.subset_span
  rw [Set.mem_range]
  let e : (Fin 1) ↪ ι :=
    ⟨fun _ => i, by intro a b _; exact Subsingleton.elim _ _⟩
  refine ⟨e, ?_⟩
  simp [e]

end StacksPart01
