/-
Copyright (c) 2026 The StacksPart01Lib authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The StacksPart01Lib Contributors
-/

import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.RingTheory.Artinian.Module
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Finiteness.Ideal
import Mathlib.RingTheory.Localization.Submodule
import Mathlib.RingTheory.Noetherian.Nilpotent

/-!
# StacksPart01Lib.CommutativeAlgebra

Small, source-faithful consequences of the commutative-algebra preliminaries.
-/

namespace StacksPart01

open Polynomial

/-- The Cayley--Hamilton identity for matrices (Stacks, Tag 00DX). -/
theorem charpoly {R n : Type*} [CommRing R] [Fintype n] [DecidableEq n]
    (A : Matrix n n R) : aeval A A.charpoly = 0 := by
  exact Matrix.aeval_self_charpoly A

/-- Finite modules over a Noetherian ring have finite presentations, finite
submodules, and the Noetherian module property (Stacks, Tag 00IK). -/
theorem noetherian_basic {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    [IsNoetherianRing R] [Module.Finite R M] :
    Module.FinitePresentation R M ∧
      (∀ N : Submodule R M, Module.Finite R N) ∧
      IsNoetherian R M := by
  refine ⟨Module.finitePresentation_of_finite R M, ?_, inferInstance⟩
  intro N
  exact Module.Finite.of_fg (Submodule.FG.of_le Module.Finite.fg_top le_top)

/-- An Artinian ring has finitely many maximal ideals (Stacks, Tag 00J7). -/
theorem artinian_finite_maximal_ideals {R : Type*} [CommSemiring R]
    [IsArtinianRing R] : {I : Ideal R | I.IsMaximal}.Finite := by
  exact IsArtinianRing.setOf_isMaximal_finite R

/-! ### Maximal minors and matrix left inverses

The Stacks Project indexes the maximal minors of a rectangular matrix by
subsets of its rows.  An injective row map is a convenient Lean encoding of
such a choice (different enumerations generate the same ideal up to signs).
-/

/-- The matrix selecting the rows in an injection `e : \kappa ↪ \ι`. -/
noncomputable def rowProjection {R ι κ : Type*} [Zero R] [One R]
    [DecidableEq ι] (e : κ ↪ ι) : Matrix κ ι R :=
  Matrix.of fun i j => if e i = j then 1 else 0

lemma rowProjection_mul {R ι κ : Type*} [CommRing R]
    [Fintype ι] [DecidableEq ι] (A : Matrix ι κ R) (e : κ ↪ ι) :
    rowProjection e * A = A.submatrix e id := by
  classical
  ext i k
  simp only [Matrix.mul_apply, rowProjection, Matrix.of_apply, Matrix.submatrix_apply,
    id_eq]
  rw [Fintype.sum_eq_single (e i)]
  · simp
  · intro b hbe
    simp [Ne.symm hbe]

/-- The ideal generated by all maximal (row) minors of a rectangular matrix.

The use of row injections avoids choosing an ordering on the finite row type;
reindexing a chosen subset changes a determinant only by a unit sign.
-/
noncomputable def minorIdeal {R ι κ : Type*} [CommRing R]
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (A : Matrix ι κ R) : Ideal R :=
  Ideal.span (Set.range fun e : κ ↪ ι => (A.submatrix e id).det)

/-- Every element of the maximal-minor ideal gives a matrix left inverse.

This is part (1) of Stacks, Lemma 07DQ. -/
@[stacks 07DQ "(1)"]
theorem matrix_left_inverse_of_mem_minorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R) {f : R}
    (hf : f ∈ minorIdeal A) :
    ∃ B : Matrix κ ι R, B * A = f • (1 : Matrix κ κ R) := by
  classical
  change f ∈ Submodule.span R
    (Set.range fun e : κ ↪ ι => (A.submatrix e id).det) at hf
  refine Submodule.span_induction (p := fun f _ => ∃ B : Matrix κ ι R,
      B * A = f • (1 : Matrix κ κ R)) ?gen ?zero ?add ?smul hf
  · intro f hf
    rcases hf with ⟨e, rfl⟩
    refine ⟨Matrix.adjugate (A.submatrix e id) * rowProjection e, ?_⟩
    rw [Matrix.mul_assoc, rowProjection_mul, Matrix.adjugate_mul]
  · refine ⟨0, ?_⟩
    simp
  · intro x y hx hy ⟨Bx, hBx⟩ ⟨By, hBy⟩
    refine ⟨Bx + By, ?_⟩
    rw [Matrix.add_mul, hBx, hBy, add_smul]
  · intro a x hx ⟨Bx, hBx⟩
    refine ⟨a • Bx, ?_⟩
    rw [Matrix.smul_mul, hBx, smul_smul]
    rfl

/-- The determinant of a square product through a rectangular matrix belongs
to the ideal generated by that matrix's maximal row minors. -/
theorem det_mul_mem_minorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R)
    (B : Matrix κ ι R) :
    (B * A).det ∈ minorIdeal A := by
  classical
  have hrows : B * A = fun i => ∑ j : ι, B i j • A j := by
    ext i k
    simp [Matrix.mul_apply]
  rw [hrows]
  change Matrix.detRowAlternating (fun i => ∑ j : ι, B i j • A j) ∈ minorIdeal A
  have hexpand :
      Matrix.detRowAlternating (fun i => ∑ j : ι, B i j • A j) =
        ∑ r : κ → ι, Matrix.detRowAlternating (fun i => B i (r i) • A (r i)) := by
    exact Matrix.detRowAlternating.toMultilinearMap.map_sum
      (g := fun i (j : ι) => B i j • A j)
  rw [hexpand]
  refine Submodule.sum_mem (minorIdeal A) (t := Finset.univ) ?_
  intro r _
  rw [AlternatingMap.map_smul_univ]
  by_cases hir : Function.Injective r
  · apply Submodule.smul_mem
    apply Submodule.subset_span
    rw [Set.mem_range]
    exact ⟨⟨r, hir⟩, rfl⟩
  · have hAr : ¬ Function.Injective (fun i => A (r i)) := by
      intro h
      apply hir
      intro i j hij
      apply h
      exact congrArg (fun x => A x) hij
    rw [Matrix.detRowAlternating.map_eq_zero_of_not_injective _ hAr, smul_zero]
    exact Submodule.zero_mem _

/-- A matrix left inverse up to a scalar puts its column-rank power in the
maximal-row-minor ideal (Stacks, Lemma 07DQ(2)). -/
@[stacks 07DQ "(2)"]
theorem matrix_left_inverse_pow_mem_minorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R) {f : R}
    (B : Matrix κ ι R)
    (hBA : B * A = f • (1 : Matrix κ κ R)) :
    f ^ Fintype.card κ ∈ minorIdeal A := by
  have hpow : f ^ Fintype.card κ = (B * A).det := by
    rw [hBA]
    simp
  rw [hpow]
  exact det_mul_mem_minorIdeal A B

/-! The rank-one and square statements below are convenient specializations
of the rectangular Cauchy--Binet direction. -/

/-- For a one-column matrix, a left inverse forces its scalar into the ideal
generated by the entries (the `m = 1` case of 07DQ(2)). -/
theorem matrix_left_inverse_one_mem_minorIdeal
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (A : Matrix ι (Fin 1) R) {f : R} (B : Matrix (Fin 1) ι R)
    (hBA : B * A = f • (1 : Matrix (Fin 1) (Fin 1) R)) :
    f ∈ minorIdeal A := by
  simpa using matrix_left_inverse_pow_mem_minorIdeal A B hBA

/-- For a square matrix, a left inverse up to a scalar puts the corresponding
power of that scalar in the maximal-minor ideal (the square specialization of
07DQ(2)). -/
theorem matrix_left_inverse_square_mem_minorIdeal
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (A B : Matrix ι ι R) {f : R}
    (hBA : B * A = f • (1 : Matrix ι ι R)) :
    f ^ Fintype.card ι ∈ minorIdeal A := by
  exact matrix_left_inverse_pow_mem_minorIdeal A B hBA

/-! The right-inverse statements are the transpose-dual form of the preceding
maximal-row-minor results.  Keeping the transpose in the definition makes the
indexing explicit while avoiding a second determinant convention. -/

/-- The ideal generated by maximal column minors of a rectangular matrix. -/
noncomputable def columnMinorIdeal {R ι κ : Type*} [CommRing R]
    [Fintype ι] [Fintype κ] [DecidableEq ι] [DecidableEq κ]
    (A : Matrix ι κ R) : Ideal R :=
  minorIdeal A.transpose

/-- The transpose-dual maximal-column-minor form of the preceding determinant
membership theorem. -/
theorem det_mul_mem_columnMinorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R)
    (B : Matrix κ ι R) :
    (A * B).det ∈ columnMinorIdeal A := by
  rw [← Matrix.det_transpose]
  rw [Matrix.transpose_mul]
  exact det_mul_mem_minorIdeal A.transpose B.transpose

/-- Every element of the maximal-column-minor ideal gives a matrix right
inverse up to that scalar (the transpose-dual of Stacks, Lemma 07DQ(1)). -/
theorem matrix_right_inverse_of_mem_columnMinorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R) {f : R}
    (hf : f ∈ columnMinorIdeal A) :
    ∃ B : Matrix κ ι R, A * B = f • (1 : Matrix ι ι R) := by
  obtain ⟨B, hB⟩ := matrix_left_inverse_of_mem_minorIdeal
    A.transpose hf
  refine ⟨B.transpose, ?_⟩
  simpa [Matrix.transpose_mul] using congrArg Matrix.transpose hB

/-- A matrix right inverse up to a scalar puts its row-rank power in the
maximal-column-minor ideal. -/
theorem matrix_right_inverse_pow_mem_columnMinorIdeal
    {R ι κ : Type*} [CommRing R] [Fintype ι] [Fintype κ]
    [DecidableEq ι] [DecidableEq κ] (A : Matrix ι κ R) {f : R}
    (B : Matrix κ ι R)
    (hAB : A * B = f • (1 : Matrix ι ι R)) :
    f ^ Fintype.card ι ∈ columnMinorIdeal A := by
  have hpow : f ^ Fintype.card ι = (A * B).det := by
    rw [hAB]
    simp
  rw [hpow]
  exact det_mul_mem_columnMinorIdeal A B

/-- In the square case, a right inverse up to `f` forces the corresponding
power of `f` into the maximal-column-minor ideal. -/
theorem matrix_right_inverse_square_mem_columnMinorIdeal
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (A B : Matrix ι ι R) {f : R}
    (hAB : A * B = f • (1 : Matrix ι ι R)) :
    f ^ Fintype.card ι ∈ columnMinorIdeal A := by
  exact matrix_right_inverse_pow_mem_columnMinorIdeal A B hAB

/-! ### Noetherian permanence

The two permanence statements below are the algebraic core of Stacks, Lemma
00FN.  We expose both the general localization form and the canonical
`Localization` specialization so later source-faithful statements can use
either presentation.
-/

/-- A finite-type algebra over a Noetherian ring is Noetherian
(Stacks, Tag 00FN). -/
theorem noetherian_of_finiteType
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.FiniteType R S] [IsNoetherianRing R] :
    IsNoetherianRing S := by
  exact Algebra.FiniteType.isNoetherianRing R S

/-- Any ring localized at a submonoid of a Noetherian ring is Noetherian
(Stacks, Tag 00FN). -/
theorem noetherian_of_isLocalization
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (M : Submonoid R) [IsLocalization M S] [IsNoetherianRing R] :
    IsNoetherianRing S := by
  exact IsLocalization.isNoetherianRing M S inferInstance

/-- The canonical localization of a Noetherian ring is Noetherian
(Stacks, Tag 00FN). -/
theorem noetherian_localization
    {R : Type*} [CommRing R] (M : Submonoid R)
    [IsNoetherianRing R] :
    IsNoetherianRing (Localization M) := by
  exact IsLocalization.instIsNoetherianRingLocalization M

/-- In a Noetherian ring, an ideal contained in a radical has a power
contained in the original ideal (Stacks, Tag 00IM). -/
theorem noetherian_ideal_power_subset
    {R : Type*} [CommRing R] [IsNoetherianRing R]
    {I J : Ideal R} (hJI : J ≤ I.radical) :
    ∃ n : ℕ, J ^ n ≤ I := by
  exact Ideal.exists_pow_le_of_le_radical_of_fg hJI
    (Ideal.fg_of_isNoetherianRing J)

/-- In a Noetherian ring, an ideal is nilpotent exactly when each of its
elements is nilpotent (Stacks, Tag 00IM). -/
theorem noetherian_locallyNilpotent_iff_nilpotent
    {R : Type*} [CommSemiring R] [IsNoetherianRing R] (I : Ideal R) :
    (∀ x ∈ I, IsNilpotent x) ↔ IsNilpotent I := by
  rw [Ideal.FG.isNilpotent_iff_le_nilradical
    (Ideal.fg_of_isNoetherianRing I)]
  constructor
  · intro h x hx
    exact mem_nilradical.mpr (h x hx)
  · intro h x hx
    exact mem_nilradical.mp (h hx)

/-- A surjective endomorphism of a finite module over a Noetherian ring is
bijective (Stacks, Tag 05G8). -/
theorem finite_module_surjective_endomorphism_bijective
    {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    [IsNoetherianRing R] [Module.Finite R M]
    (f : Module.End R M) (hf : Function.Surjective f) :
    Function.Bijective f := by
  exact IsNoetherian.bijective_of_surjective_endomorphism f hf

/-- An injective endomorphism of an Artinian module is bijective. -/
theorem artinian_module_injective_endomorphism_bijective
    {R M : Type*} [Semiring R] [AddCommMonoid M] [Module R M]
    [IsArtinian R M] (f : Module.End R M) (hf : Function.Injective f) :
    Function.Bijective f := by
  exact IsArtinian.bijective_of_injective_endomorphism f hf

end StacksPart01
