/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import AlgebraicJacobian.Cohomology.AffineSerreVanishing
import AlgebraicJacobian.Cohomology.HigherDirectImagePresheaf
import AlgebraicJacobian.Cohomology.AcyclicResolution

/-!
# Higher direct images along open immersions of affine opens

This file establishes `lem:open_immersion_pushforward_comp`:

1. `higherDirectImage_openImmersion_acyclic`: for an open immersion `j : U ↪ X` of an
   affine open `U` into a separated scheme `X`, the higher direct images `R^q j_* H` vanish
   for `q ≥ 1` and any quasi-coherent `O_U`-module `H`.

2. `higherDirectImage_openImmersion_comp` (pinned declaration): consequently, for any
   morphism `f : X ⟶ S` and quasi-coherent `H` on `U`, there is a canonical isomorphism
   `R^k f_*(j_* H) ≅ R^k (f ∘ j)_* H`.

Blueprint: `lem:open_immersion_pushforward_comp`.
Source: Stacks Project, Cohomology of Schemes, `lemma-relative-affine-vanishing`.
-/

universe u

open CategoryTheory Limits

/-! ## Project-local Mathlib supplement — reflecting `IsZero` through a faithful functor -/

namespace CategoryTheory.Functor

/-- **A faithful functor that preserves zero morphisms reflects the zero object.**
If `F` is faithful and preserves zero morphisms and `F.obj X` is a zero object, then `X`
is a zero object. (Three-line proof off `IsZero.iff_id_eq_zero` + `Functor.map_injective`.)

Project-local Mathlib supplement (category theory).  A copy of the same lemma in
`CechAugmentedResolution.lean`; reproduced here because that sibling file is not in this
file's import chain. -/
lemma isZero_of_faithful_preservesZeroMorphisms
    {C D : Type*} [Category C] [Category D] [Limits.HasZeroMorphisms C] [Limits.HasZeroMorphisms D]
    (F : C ⥤ D) [F.PreservesZeroMorphisms] [F.Faithful] {Y : C}
    (h : Limits.IsZero (F.obj Y)) : Limits.IsZero Y := by
  rw [Limits.IsZero.iff_id_eq_zero] at h ⊢
  apply F.map_injective
  rw [F.map_id, F.map_zero]
  exact h

end CategoryTheory.Functor

/-! ## Project-local Mathlib supplement — sheafification of a sectionwise-locally-zero presheaf -/

namespace CategoryTheory.GrothendieckTopology

open Opposite in
/-- **The sheafification of a presheaf whose sections are locally zero vanishes.**
If for every object `U` and every section `s : Q(U)` there is a covering sieve `S ∈ J U`
on which `s` restricts to `0`, then the sheafification of `Q` is a zero object.

This is the *sectionwise* (local-injectivity) strengthening of
`isZero_presheafToSheaf_of_locally_isZero`: that lemma requires the *objectwise* vanishing
`Q.obj (op V) = 0` for every member `V` of a single covering sieve, which forces the
vanishing to hold on a downward-closed family.  Here only the restricted *section* need
vanish, so the witnessing sieve can be generated by a cofinal *basis* of "good" opens
(e.g. the affine opens, where the section group vanishes) even though the basis itself is
not downward closed.  The local injectivity of `0 : Q ⟶ Z` (`Z` the constant zero
presheaf) is read off from the hypothesis applied to `x - y`; local surjectivity is free.
Project-local Mathlib supplement (site theory). -/
lemma isZero_presheafToSheaf_of_sections_locally_zero {C : Type*} [Category C]
    (J : GrothendieckTopology C) [HasSheafify J AddCommGrpCat.{u}]
    [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
    {Q : Cᵒᵖ ⥤ AddCommGrpCat.{u}}
    (h : ∀ (U : C) (s : ToType (Q.obj (op U))), ∃ S : Sieve U, S ∈ J U ∧
      ∀ ⦃V : C⦄ ⦃g : V ⟶ U⦄, S.arrows g → (ConcreteCategory.hom (Q.map g.op)) s = 0) :
    IsZero ((presheafToSheaf J AddCommGrpCat.{u}).obj Q) := by
  let Z : Cᵒᵖ ⥤ AddCommGrpCat.{u} := (Functor.const Cᵒᵖ).obj (AddCommGrpCat.of PUnit)
  have hZobj : ∀ x : Cᵒᵖ, IsZero (Z.obj x) := by
    intro x
    change IsZero (AddCommGrpCat.of PUnit)
    exact AddCommGrpCat.isZero_of_subsingleton _
  have hZ : IsZero Z := (Functor.isZero_iff Z).mpr hZobj
  haveI hli : Presheaf.IsLocallyInjective J (0 : Q ⟶ Z) := by
    refine ⟨?_⟩
    intro X x y _
    obtain ⟨S, hS, hSzero⟩ := h X.unop (x - y)
    apply J.superset_covering _ hS
    intro V g hg
    change (ConcreteCategory.hom (Q.map g.op)) x = (ConcreteCategory.hom (Q.map g.op)) y
    have h0 : (ConcreteCategory.hom (Q.map g.op)) (x - y) = 0 := hSzero hg
    rw [map_sub] at h0
    exact sub_eq_zero.mp h0
  haveI hls : Presheaf.IsLocallySurjective J (0 : Q ⟶ Z) := by
    refine ⟨?_⟩
    intro U s
    refine J.superset_covering (fun V g _ => ?_) (J.top_mem U)
    refine ⟨0, ?_⟩
    haveI : Subsingleton (Z.obj (op V)) := AddCommGrpCat.subsingleton_of_isZero (hZobj (op V))
    exact Subsingleton.elim _ _
  exact isZero_presheafToSheaf_obj_of_isLocallyBijective J (0 : Q ⟶ Z) hZ

end CategoryTheory.GrothendieckTopology

namespace AlgebraicGeometry

open Scheme.Modules

variable {U X S : Scheme.{u}}

/- Planner strategy:
Part (1): `R^q j_* H` is the sheafification of `V ↦ H^q(j⁻¹V, H)` (presheaf description
`higher_direct_image_presheaf`, Stacks 01XJ); for affine `V`, `j⁻¹V = U ∩ V` is affine (U affine,
X separated), so `affine_serre_vanishing` kills `H^q` for `q ≥ 1`; affine opens are a basis ⇒
`R^q j_* H = 0`. Part (2): take an injective resolution `H → I•`; `j_* I•` is a resolution of
`j_* H` (each `j_* Iⁿ` is `j_*`-acyclic by (1)) and each `j_* Iⁿ` is `f_*`-acyclic (same presheaf
+ Serre-vanishing argument on `U ∩ f⁻¹V`); so `j_* I•` is an `f_*`-acyclic resolution of `j_* H`,
and the P4 acyclic-resolution comparison (`acyclic_resolution_computes_derived` /
`rightDerivedIsoOfAcyclicResolution`) with `G = f_*` gives `R^k f_*(j_* H) ≅ H^k(f_*(j_* I•)) =
H^k((f∘j)_* I•) = R^k (f∘j)_* H`, using `f_* ∘ j_* = (f∘j)_*`. Blueprint:
`lem:open_immersion_pushforward_comp`. Source: Stacks `lemma-relative-affine-vanishing`.
-/

/-- **Higher direct images of an affine open immersion vanish** (part (1) of blueprint
`lem:open_immersion_pushforward_comp`; Stacks `lemma-relative-affine-vanishing`).

For an open immersion `j : U ↪ X` where `U` is affine and `X` is separated, the morphism
`j` is affine (since for any affine open `V ⊆ X`, `j⁻¹V = U ∩ V` is affine by separatedness).
Therefore `R^q j_* H = 0` for every `q ≥ 1` and every quasi-coherent `O_U`-module `H`.

Proof route: by `higherDirectImage_iso_sheafify_presheafHomology`, `R^q j_* H` is the
sheafification of `V ↦ H^q(j⁻¹V, H)`. For affine `V`, `j⁻¹V = U ∩ V` is affine (`U` affine
+ `X` separated), and `affine_serre_vanishing` kills `H^q` for `q ≥ 1`. Since affine opens
form a basis, the presheaf homology is locally zero, and the site lemmas
`isZero_presheafToSheaf_obj_of_isLocallyBijective` (in `CechHigherDirectImage.lean`,
importable via `AffineSerreVanishing`) collapse the sheafification to zero. -/
private lemma isAffineHom_of_affine_separated (j : U ⟶ X) [IsAffine U] [X.IsSeparated] :
    IsAffineHom j := by
  have hg : IsSeparated (terminal.from X) := Scheme.IsSeparated.isSeparated_terminal_from
  have hcomp : IsAffineHom (j ≫ terminal.from X) := by
    have he : j ≫ terminal.from X = terminal.from U := terminal.hom_ext _ _
    rw [he]; infer_instance
  exact IsAffineHom.of_comp j (terminal.from X)

theorem higherDirectImage_openImmersion_acyclic [HasInjectiveResolutions U.Modules]
    (j : U ⟶ X) [IsOpenImmersion j] [IsAffine U] [X.IsSeparated]
    (H : U.Modules) (hH : H.IsQuasicoherent) (q : ℕ) (hq : 0 < q) :
    IsZero (higherDirectImage j q H) := by
  -- `j` is an affine morphism (open immersion of an affine into a separated scheme),
  -- so the preimage of every affine open `V ⊆ X` is the affine open `j⁻¹V = U ∩ V`.
  haveI : IsAffineHom j := isAffineHom_of_affine_separated j
  -- Presheaf description (Stacks 01XJ): `Rᵠ j_* H ≅ sheafify(V ↦ Hᵠ((j_* I•)(V)))`
  -- for any injective resolution `I` of `H`. Reduce to the vanishing of that sheafification.
  refine IsZero.of_iso ?_
    (higherDirectImage_iso_sheafify_presheafHomology j q (injectiveResolution H))
  set α : X.ringCatSheaf.obj ⟶ X.ringCatSheaf.obj := 𝟙 X.ringCatSheaf.obj with hα
  set P := (pushforwardResolutionPresheafComplex j (injectiveResolution H)).homology q with hP
  -- Reflect `IsZero` through the faithful, zero-preserving forgetful functor `toSheaf`.
  apply Functor.isZero_of_faithful_preservesZeroMorphisms (SheafOfModules.toSheaf X.ringCatSheaf)
  -- Transport across the sheafification square
  -- `toSheaf ∘ sheafification ≅ presheafToSheaf ∘ toPresheaf`.
  refine IsZero.of_iso ?_ ((PresheafOfModules.sheafificationCompToSheaf α).app P)
  set Q := (PresheafOfModules.toPresheaf X.ringCatSheaf.obj).obj P with hQ
  -- KEY VANISHING (genuine cohomological gap): the presheaf homology `Q` is a *zero object*
  -- over every affine open `W ⊆ X`, because `j⁻¹W` is affine (`j` is an affine morphism) and
  -- `affine_serre_vanishing` kills `Hᵠ(j⁻¹W, H)` for `q ≥ 1`.
  have hSec : ∀ (W : TopologicalSpace.Opens X), IsAffineOpen W →
      IsZero (Q.obj (Opposite.op W)) := by
    intro W hW
    -- Evaluate-at-`W` the presheaf complex; this functor preserves homology, so
    -- `Q.obj (op W) ≅ Hᵠ(Γ(W, f_* I•)) = Hᵠ(j⁻¹W, H)`, which vanishes for affine `j⁻¹W`.
    set GW := PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W) with hGW
    set Kp := pushforwardResolutionPresheafComplex j (injectiveResolution H) with hKp
    refine IsZero.of_iso ?_ (GW.mapHomologyIso' (ComplexShape.up ℕ) Kp q).symm
    -- The section complex `n ↦ Γ(W, f_* I^n) = Γ(j⁻¹W, I^n)` is the image of the chosen
    -- injective resolution of `H` under the additive sections-over-`j⁻¹W` functor `Φ`.
    set Φ : U.Modules ⥤ AddCommGrpCat :=
      Scheme.Modules.pushforward j ⋙ SheafOfModules.forget X.ringCatSheaf ⋙
        PresheafOfModules.restrictScalars α ⋙ PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
        (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W) with hΦ
    have hcomplex : (GW.mapHomologicalComplex (ComplexShape.up ℕ)).obj Kp
        = (Φ.mapHomologicalComplex (ComplexShape.up ℕ)).obj (injectiveResolution H).cocomplex :=
      rfl
    rw [hcomplex]
    -- `isoRightDerivedObj` recognises this homology as the `q`-th right derived sections
    -- functor `Rᵠ Γ(j⁻¹W, -)` applied to `H`, i.e. the absolute cohomology `Hᵠ(j⁻¹W, H)`.
    refine IsZero.of_iso ?_ ((injectiveResolution H).isoRightDerivedObj Φ q).symm
    -- RESIDUAL (Bridge 2): `Hᵠ(j⁻¹W, H) = 0` for `q ≥ 1`.  `j⁻¹W` is affine (`j` is an
    -- affine morphism), so this is Serre vanishing on the affine `j⁻¹W` (`affine_serre_vanishing`
    -- transported across `j⁻¹W ≅ Spec Γ(j⁻¹W, 𝒪)`).
    sorry
  -- Since affine opens form a basis of `X`, every section of `Q` restricts to `0` on the
  -- affine opens contained in its domain, so `Q` is sectionwise locally zero and its
  -- sheafification vanishes.
  apply CategoryTheory.GrothendieckTopology.isZero_presheafToSheaf_of_sections_locally_zero
    (Opens.grothendieckTopology X) (Q := Q)
  intro U s
  refine ⟨{ arrows := fun {V} _ => ∃ W : TopologicalSpace.Opens X,
              IsAffineOpen W ∧ V ≤ W ∧ W ≤ U,
            downward_closed := ?_ }, ?_, ?_⟩
  · rintro V V' g ⟨A, hA, hVA, hAU⟩ h
    exact ⟨A, hA, le_trans (leOfHom h) hVA, hAU⟩
  · -- membership in the opens topology: every point of `U` has an affine basis neighbourhood
    intro x hx
    obtain ⟨W, hWmem, hxW, hWU⟩ :=
      (TopologicalSpace.Opens.isBasis_iff_nbhd.mp (Scheme.isBasis_affineOpens X)) hx
    exact ⟨W, homOfLE hWU, ⟨W, hWmem, le_refl W, hWU⟩, hxW⟩
  · -- the restriction of `s` to a sieve member `V ≤ A ≤ U` (with `A` affine) factors through
    -- `Q.obj (op A) = 0`, hence vanishes.
    rintro V g ⟨A, hA, hVA, hAU⟩
    haveI : Subsingleton (ToType (Q.obj (Opposite.op A))) :=
      AddCommGrpCat.subsingleton_of_isZero (hSec A hA)
    have hgfac : g.op = (homOfLE hAU).op ≫ (homOfLE hVA).op := by
      rw [← op_comp]; congr 1
    rw [hgfac, Q.map_comp, ConcreteCategory.comp_apply,
      Subsingleton.elim ((ConcreteCategory.hom (Q.map (homOfLE hAU).op)) s) 0, map_zero]

/-- **Composition formula for higher direct images across an open immersion** (pinned
declaration; blueprint `lem:open_immersion_pushforward_comp`, part (2); Stacks
`lemma-relative-affine-vanishing`).

Let `j : U ↪ X` be an open immersion of an affine open `U` into a separated scheme `X`,
and `f : X ⟶ S` any morphism. For every quasi-coherent `O_U`-module `H` and every `k ≥ 0`:
```
  R^k f_*(j_* H) ≅ R^k (f ∘ j)_* H.
```
Proof route: choose an injective resolution `H → I•` in `U.Modules`; apply `j_*`
degreewise to get an `f_*`-acyclic resolution `j_* I•` of `j_* H`
(`higherDirectImage_openImmersion_acyclic` for `j_*`-acyclicity, extended to
`f_*`-acyclicity via the same Serre-vanishing argument on `U ∩ f⁻¹V`); then
`Functor.rightDerivedIsoOfAcyclicResolution` with `G = (pushforward f)` and the identity
`(pushforward f) ∘ (pushforward j) = pushforward (j ≫ f)` give the stated isomorphism. -/
theorem higherDirectImage_openImmersion_comp
    [HasInjectiveResolutions X.Modules] [HasInjectiveResolutions U.Modules]
    (j : U ⟶ X) [IsOpenImmersion j] [IsAffine U] [X.IsSeparated]
    (f : X ⟶ S) (H : U.Modules) (hH : H.IsQuasicoherent) (k : ℕ) :
    Nonempty (higherDirectImage f k ((pushforward j).obj H) ≅
              higherDirectImage (j ≫ f) k H) := by
  haveI : IsAffineHom j := isAffineHom_of_affine_separated j
  -- Structural plan (all categorical building blocks below are verified to exist):
  --   • `G := Scheme.Modules.pushforward f` is additive and preserves finite limits
  --     (`inferInstance`), so `Functor.rightDerivedIsoOfAcyclicResolution` applies to it.
  --   • The pushed-forward injective resolution `K := (pushforward j).mapHomologicalComplex I•`
  --     is a candidate acyclic resolution of `j_* H = (pushforward j).obj H`.
  --   • `pushforwardComp j f : pushforward j ⋙ pushforward f ≅ pushforward (j ≫ f)` turns
  --     `H^k(G(K))` into `H^k((j ≫ f)_* I•) = R^k (j ≫ f)_* H`.
  -- RESIDUAL (genuine cohomological gaps, handed off — each depends on Part (1)'s residual):
  --   (a) `K` is exact in positive degrees and resolves `j_* H` (i.e. `j_* I•` is a
  --       resolution of `j_* H`) — this is `j_*`-acyclicity, the content of
  --       `higherDirectImage_openImmersion_acyclic` applied to each `Iⁿ` and to `H`.
  --   (b) each term `(pushforward j).obj (Iⁿ)` is `(pushforward f)`-acyclic
  --       (`Functor.IsRightAcyclic`), i.e. `R^k f_*(j_* Iⁿ) = 0` for `k ≥ 1` — the same
  --       Serre-vanishing argument on the affine `U ∩ f⁻¹V` (generalises Part (1) from
  --       `j_*` to `f_*` via the presheaf description on `f⁻¹V`).
  -- Then `Functor.rightDerivedIsoOfAcyclicResolution (pushforward f) K (j_* H) e (a) k`
  -- composed with the `pushforwardComp` transport gives the stated iso.
  sorry

end AlgebraicGeometry
