/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.GaloisQuotientGlue

/-!
# Stable opens on affine Galois quotient charts

Let `L/K` be a finite extension, let `X` carry a semilinear `Gal(L/K)`-action,
and let `U` be a stable affine open of `X`.  The affine quotient chart is
`Spec (Γ(U)^Gal(L/K))`.  If `V ≤ U` is stable, the invariant norm construction
of `GaloisQuotientGlue` covers `V` by basic opens `D(N)` for invariant sections
`N ∈ Γ(U)`.

This file constructs the corresponding open of the quotient chart as the union
of the basic opens cut out by those same elements in `Γ(U)^Gal(L/K)`.  Its main
result is the exact saturation identity

`stableAffineQuotientMap ⁻¹(V/Gal(L/K)) = U.ι ⁻¹(V)`.

Thus stable overlaps already determine honest opens on the affine quotient
charts.  Constructing and gluing the resulting overlap isomorphisms is a
separate step.

## Main declarations

* `SemilinearAction.affineQuotientMap` is the canonical map
  `Spec A ⟶ Spec (A^Gal(L/K))`.
* `SemilinearGalAction.quotientOpenOfStableSubopen` is the quotient-chart open
  generated by invariant basic opens contained in `V`.
* `SemilinearGalAction.stableAffineQuotientMap` is the quotient map on a stable
  affine chart.
* `SemilinearGalAction.stableAffineQuotientMap_preimage_quotientOpen` proves the
  saturation identity above.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits AlgebraicGeometry TopologicalSpace

namespace AlgebraicJacobian.GaloisDescent

namespace SemilinearAction

variable (K L : Type u) [Field K] [Field L] [Algebra K L]
variable (A : Type u) [CommRing A] [Algebra K A] [Algebra L A] [IsScalarTower K L A]
variable [MulSemiringAction (L ≃ₐ[K] L) A] [IsSemilinear K L A]

/-- The canonical affine quotient map `Spec A ⟶ Spec (A^Gal(L/K))`, induced by
the inclusion of the invariant subalgebra. -/
noncomputable def affineQuotientMap :
    Spec (CommRingCat.of A) ⟶ Spec (CommRingCat.of (invariantsSubalgebra K L A)) :=
  Spec.map (CommRingCat.ofHom (invariantsSubalgebra K L A).val)

end SemilinearAction

namespace SemilinearGalAction

variable {K L : Type u} [Field K] [Field L] [Algebra K L]
variable {X : Scheme.{u}} {f : X ⟶ Spec (CommRingCat.of L)}
variable (ρ : SemilinearGalAction K L X f) {U : X.Opens} (hU : ρ.IsStableOpen U)

/-- The open of the affine quotient chart generated by invariant basic opens
`D(N) ≤ V`.  Each index supplies the invariant element
`⟨N, hN⟩ : Γ(U)^Gal(L/K)` cutting out the corresponding quotient-side basic open. -/
noncomputable def quotientOpenOfStableSubopen (V : X.Opens) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    (Spec (CommRingCat.of
      (SemilinearAction.invariantsSubalgebra K L Γ(X, U)))).Opens := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  exact ⨆ i : InvariantBasicOpenIndex ρ hU V,
    PrimeSpectrum.basicOpen
      (⟨i.1, i.2.1⟩ : SemilinearAction.invariantsSubalgebra K L Γ(X, U))

/-- The canonical quotient map from a stable affine chart to the spectrum of
the invariant subalgebra of its section ring. -/
noncomputable def stableAffineQuotientMap (hUa : IsAffineOpen U) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    U.toScheme ⟶ Spec (CommRingCat.of
      (SemilinearAction.invariantsSubalgebra K L Γ(X, U))) := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  exact hUa.isoSpec.hom ≫ SemilinearAction.affineQuotientMap K L Γ(X, U)

/-- **A stable subopen is the pullback of an open on the affine quotient chart.**

The quotient-side open is the union of basic opens defined by invariant sections
whose source-side basic opens lie in `V`.  The invariant-basic-open covering
theorem identifies their source-side union with `V`; functoriality of basic opens
under `Spec` then gives the claimed equality. -/
theorem stableAffineQuotientMap_preimage_quotientOpen [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V : X.Opens} (hVU : V ≤ U)
    (hV : ρ.IsStableOpen V) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    (stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ quotientOpenOfStableSubopen ρ hU V =
      U.ι ⁻¹ᵁ V := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  rw [stableAffineQuotientMap, Scheme.Hom.comp_preimage,
    quotientOpenOfStableSubopen, Scheme.Hom.preimage_iSup,
    Scheme.Hom.preimage_iSup]
  simp only [SemilinearAction.affineQuotientMap]
  rw [hUa.isoSpec_hom]
  calc
    (⨆ i : InvariantBasicOpenIndex ρ hU V,
        U.toSpecΓ ⁻¹ᵁ
          (PrimeSpectrum.basicOpen (i.1 : Γ(X, U)) :
            (Spec (CommRingCat.of Γ(X, U))).Opens))
        = ⨆ i : InvariantBasicOpenIndex ρ hU V,
            U.ι ⁻¹ᵁ X.basicOpen i.1 := by
              congr 1
              funext i
              exact U.toSpecΓ_preimage_basicOpen i.1
    _ = U.ι ⁻¹ᵁ (⨆ i : InvariantBasicOpenIndex ρ hU V, X.basicOpen i.1) :=
      (Scheme.Hom.preimage_iSup U.ι _).symm
    _ = U.ι ⁻¹ᵁ V := by rw [ρ.iSup_invariantBasicOpen_eq hU hUa hVU hV]

end SemilinearGalAction

end AlgebraicJacobian.GaloisDescent
