import AlgebraicJacobian.Picard.Pic0ChartRestrictedFibreSat
open AlgebraicGeometry
#print axioms AlgebraicGeometry.pic0Sigma_obj_subsingleton_of_isEmpty
#print axioms AlgebraicGeometry.isEmpty_coe_bot_opens
#print axioms AlgebraicGeometry.restrictedChartFibre_bot
#print axioms AlgebraicGeometry.isChartUniv_bot
#print axioms AlgebraicGeometry.not_coverageContainment_bot
#print axioms AlgebraicGeometry.range_subset_range_top_ι
#print axioms AlgebraicGeometry.isOpenImmersion_presheaf_abelSigmaChart_of_restrictedChartFibre_top
#print axioms AlgebraicGeometry.not_restrictedChartFibre_top_of_not_injective
-- CONTROL: must show sorryAx
#print axioms AlgebraicGeometry.Jacobian
