/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.RiemannRoch.Adelic.BoundedVanishing

/-!
# Adelic Riemann–Roch — global generation above the bound

This file closes the **third** of the three gaps the vanishing lane kept apart
(`Adelic/BoundedVanishing.lean`, module docstring): *global generation*.  Until now
that gap was recorded as "not addressed at all"; the statements below address it, and
the docstrings there and in `Adelic/SectionBounds.lean` are updated accordingly.

## What global generation means here

`𝒪(D)` is **generated by global sections at a prime divisor `P`** exactly when some
global section attains the pole bound at `P`:

`∃ f ∈ Γ(⊤, 𝒪(D)), f ≠ 0 ∧ ord_P f = -D(P)`.

Such an `f` differs from a local generator of `𝒪(D)` at `P` by a unit of the DVR
`𝒪_P`, so it generates the stalk.  This is `GeneratedAt` below.  The sharper
statement is that the *whole* residue field is reached — the evaluation map

`Γ(⊤, 𝒪(D)) / Γ(⊤, 𝒪(D − P)) → κ(P)`

is not merely nonzero but **onto** (`localStepMapₖ_bijective_of_vanishing`).

## The mechanism: two vanishings, not one

The evaluation map is *always* injective — that is `localStepMapₖ_injective`, the
elementary half of node N14, and it is what makes `ℓ(D) − ℓ(D−P) ≤ [κ(P):k]`.  It is
onto exactly when that inequality is an equality, and the ledger converts the
equality into a statement about `h¹`:

`ℓ(D) − ℓ(D−P) = [κ(P):k] + h¹(D) − h¹(D−P)`.

So surjectivity follows from `h¹(D) = 0` **and** `h¹(D−P) = 0`.  This is why global
generation is *strictly* more than bounded vanishing and why the threshold moves:
`deg_k (D − P) = deg_k D − [κ(P):k]`, so to put `D − P` above the vanishing bound `b`
one needs `deg_k D ≥ b + [κ(P):k]` — the bound raised by the residue degree *at that
point*.

## The three gaps, restated

With this file the ledger of gaps reads:

1. **Single-field bounded vanishing** — assembled in `BoundedVanishing.lean` from
   three named inputs (base vanishing, peel, closed ledger); the first two are jointly
   equivalent to cone-vanishing (`coneVanishing_iff_base_and_peel`), so this is a
   reduction and not a discharge.
2. **Extension uniformity** — still untouched, and still not even *statable*: the
   invariants here are pinned on a chosen 2-affine cover, and
   `RiemannRoch/CurveBaseChange.lean` does not transport that cover to `C_κ`.
3. **Global generation** — **this file**, conditional on exactly the same inputs as
   (1) and nothing more, with the threshold shifted by the residue degree.  The
   pointwise form (`generatedAt_of_bound`) is unconditional in `P`; the *uniform*
   form (`forall_generatedAt_of_bound_of_residueDeg_le`) needs a bound `r` on residue
   degrees, which is a genuine extra hypothesis over a general `k` (residue degrees of
   closed points are unbounded over a finite field) and is `r = 1` over an
   algebraically closed base.

## Provenance

Rederived in the AJC adelic abstractions.  The sibling `AJCR` proves global generation
on the `divisorSheaf` substrate via an evaluation-map/`Serre`-twist argument; none of
those identifiers exist here.  What is reused is the *idea* that global generation is
the equality case of the section-drop bound; the mechanism above (rank–nullity against
`finrank_localStepTgt`) is the adelic form and is cheaper, since the injectivity half
is already landed as N14.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits IsDedekindDomain
open scoped WithZero

namespace AlgebraicGeometry
namespace Adelic

/-! ## §1. The one-point-down divisor `D − P` -/

section PointDown

variable {X : Scheme.{u}} [IsIntegral X] [IsLocallyNoetherian X]
    [Scheme.IsRegularInCodimensionOne X]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **The coefficient of `D − P` at `P` is one less.** -/
theorem sub_pointDivisor_apply_self (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P =
      (show X.PrimeDivisor →₀ ℤ from D) P - 1 := by
  rw [show (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P =
        (show X.PrimeDivisor →₀ ℤ from D) P -
          (show X.PrimeDivisor →₀ ℤ from pointDivisor P) P from Finsupp.sub_apply _ _ _,
    pointDivisor, Finsupp.single_eq_same]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **`D − P` agrees with `D` off `P`.** -/
theorem sub_pointDivisor_apply_of_ne (D : X.WeilDivisor) {P Q : X.PrimeDivisor}
    (h : Q ≠ P) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q =
      (show X.PrimeDivisor →₀ ℤ from D) Q := by
  rw [show (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q =
        (show X.PrimeDivisor →₀ ℤ from D) Q -
          (show X.PrimeDivisor →₀ ℤ from pointDivisor P) Q from Finsupp.sub_apply _ _ _,
    pointDivisor, Finsupp.single_eq_of_ne h, sub_zero]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **`D − P ≤ D`.** -/
theorem sub_pointDivisor_le (D : X.WeilDivisor) (P Q : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q ≤
      (show X.PrimeDivisor →₀ ℤ from D) Q := by
  rcases eq_or_ne Q P with rfl | hne
  · rw [sub_pointDivisor_apply_self]; omega
  · rw [sub_pointDivisor_apply_of_ne D hne]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **The one-point step hypothesis for the pair `(D − P, D)`.** -/
theorem sub_pointDivisor_step (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D) P =
      (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P + 1 := by
  rw [sub_pointDivisor_apply_self]; omega

end PointDown

/-! ## §2. The evaluation map and its surjectivity

The **evaluation map** at `P` for the divisor `D` is `localStepMapₖ` for the pair
`(D − P, D)` at `U = ⊤`:

`Γ(⊤, 𝒪(D)) / Γ(⊤, 𝒪(D − P)) → orderGe P (-D(P)+1-1) ⧸ orderGe P (-D(P)+1) ≅ κ(P)`.

It is always injective (`localStepMapₖ_injective`).  It is surjective exactly when the
section drop is maximal, and rank–nullity turns that into the two-vanishing condition.
-/

section Evaluation

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **The evaluation map at `P`.**  `localStepMapₖ` for the one-point step
`D − P ≤ D` on the whole space; its target is a single-point valuation quotient, which
`finrank_localStepTgt` identifies numerically with the residue field `κ(P)`. -/
noncomputable def evalMap (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    localStepDom k ⊤ (D - pointDivisor P) D →ₗ[k]
      localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P) :=
  localStepMapₖ k (TopologicalSpace.Opens.mem_top P.point)
    (sub_pointDivisor_step D P)

/-- **The evaluation map is injective** — the elementary half of node N14, restated at
the pair `(D − P, D)`.  Unconditional: no ledger, no vanishing. -/
theorem evalMap_injective (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    Function.Injective (evalMap k D P) :=
  localStepMapₖ_injective k (TopologicalSpace.Opens.mem_top P.point)
    (sub_pointDivisor_step D P) (sub_pointDivisor_le D P)
    (fun _ hQ => sub_pointDivisor_apply_of_ne D hQ)

end Evaluation

section EvalSurjective

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **The section drop is exactly the residue degree when both `h¹` vanish.**

The closed ledger reads `χ(D) − χ(D−P) = deg_k D − deg_k (D−P) = [κ(P):k]`, and
`χ = ℓ − h¹`, so

`ℓ(D) − ℓ(D−P) = [κ(P):k] + h¹(D) − h¹(D−P)`.

Under the two vanishings `h¹(D) = h¹(D−P) = 0` the correction terms drop out and the
section drop is *maximal*.  Compare `ell_le_ell_add_residueDeg` (`SectionBounds.lean`),
which gives the inequality `≤` unconditionally: this is its equality case, and the
input needed for equality is precisely a pair of vanishings, not one. -/
theorem ell_sub_ell_sub_pointDivisor_eq
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P))) :
    (ell k D : ℤ) - ell k (D - pointDivisor P) = residueDeg k P := by
  have h1 := h1dim_eq_zero_of_subsingleton k U₀ U₁ hD
  have h2 := h1dim_eq_zero_of_subsingleton k U₀ U₁ hDP
  have hchiD := hledger D
  have hchiDP := hledger (D - pointDivisor P)
  have hdeg : degK k D - degK k (D - pointDivisor P) = residueDeg k P := by
    rw [degK_sub, degK_pointDivisor]; ring
  rw [chi, h1] at hchiD
  rw [chi, h2] at hchiDP
  omega

/-- **The evaluation map is surjective** — hence bijective, since it is always
injective.  Global generation in its sharpest adelic form: not merely "some section
attains the pole bound at `P`", but "*every* residue class at `P` is attained".

The proof is a rank count: the domain has dimension `ℓ(D) − ℓ(D−P)`
(`finrank_localStepDom`, rank–nullity), the target has dimension `[κ(P):k]`
(`finrank_localStepTgt`), the two agree by
`ell_sub_ell_sub_pointDivisor_eq`, and an injective map between spaces of equal finite
dimension is onto (`LinearMap.injective_iff_surjective_of_finrank_eq_finrank`).

Note which finiteness is needed and which is not: `Module.Finite k (sectionSub k ⊤ D)`
enters through rank–nullity, and `Module.Finite k (localStepTgt k P 1)` is the residue
finiteness `[κ(P):k] < ∞` — the same gated keystone input node N14 already takes. -/
theorem evalMap_surjective
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P)))
    [Module.Finite k (sectionSub k ⊤ D)]
    [Module.Finite k (localStepTgt k P 1)] :
    Function.Surjective (evalMap k D P) := by
  -- the domain is finite-dimensional (a quotient of a finite-dimensional space)
  haveI : Module.Finite k (localStepDom k ⊤ (D - pointDivisor P) D) := inferInstance
  haveI : Module.Finite k
      (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    have hrank := finrank_localStepTgt k P
      (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)
    obtain ⟨t, ht, htord⟩ :=
      exists_order_eq P (1 - -(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)
    exact Module.Finite.equiv
      (LinearEquiv.ofBijective (residueShift k t ht htord)
        ⟨residueShift_injective k t ht htord,
          residueShift_surjective k t ht htord⟩).symm
  -- the two dimensions agree
  have hdim : Module.finrank k (localStepDom k ⊤ (D - pointDivisor P) D) =
      Module.finrank k
        (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    rw [finrank_localStepTgt]
    have hrn := finrank_localStepDom k ⊤
      (sectionSub_mono k ⊤ (sub_pointDivisor_le D P))
    have hdrop := ell_sub_ell_sub_pointDivisor_eq k U₀ U₁ hledger D P hD hDP
    simp only [ell] at hdrop
    omega
  exact (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hdim).mp
    (evalMap_injective k D P)

end EvalSurjective

/-! ## §3. Global generation as a statement about sections

`evalMap_surjective` is the sharp form, but it is phrased on a subquotient.  The form a
consumer wants is about an actual rational function: *some global section of `𝒪(D)`
attains the pole bound at `P`*.  That is `GeneratedAt` below, and it follows from
surjectivity together with the nontriviality of `κ(P)` (`1 ≤ [κ(P):k]`).
-/

section GeneratedAt

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **`𝒪(D)` is generated by global sections at `P`.**  Some global section attains the
pole bound at `P` exactly: `ord_P f = -D(P)`.

Such an `f` generates the stalk `𝒪(D)_P` over `𝒪_P`, since any two elements of the
fractional ideal `𝔪_P^{-D(P)}` of minimal order differ by a unit.  Stated on the order
rather than on the stalk so that it is checkable in the adelic language; a section with
`ord_P f > -D(P)` is exactly one that *fails* to generate, i.e. vanishes at `P` as a
section of the twist. -/
def GeneratedAt (D : X.WeilDivisor) (P : X.PrimeDivisor) : Prop :=
  ∃ f : X.functionField, f ∈ sectionSub k ⊤ D ∧ f ≠ 0 ∧
    Scheme.RationalMap.order P f = -(show X.PrimeDivisor →₀ ℤ from D) P

/-- **Surjectivity of the evaluation map gives global generation at `P`.**

`κ(P)` is nontrivial (`1 ≤ [κ(P):k]`, `one_le_residueDeg`), so the target of `evalMap`
has a nonzero element; a preimage of it is a global section `f` of `𝒪(D)` whose class in
`orderGe P (-D(P)) / orderGe P (-D(P)+1)` is nonzero, i.e. with
`ord_P f < -D(P) + 1`.  Being a section of `𝒪(D)` gives the reverse `ord_P f ≥ -D(P)`,
so `ord_P f = -D(P)`. -/
theorem generatedAt_of_evalMap_surjective (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hsurj : Function.Surjective (evalMap k D P))
    [Module.Finite k (localStepTgt k P 1)] :
    GeneratedAt k D P := by
  -- the target is nontrivial: its dimension is `[κ(P):k] ≥ 1`
  haveI : Nontrivial
      (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    refine Module.nontrivial_of_finrank_pos (R := k) ?_
    rw [finrank_localStepTgt]
    exact one_le_residueDeg k P
  obtain ⟨z, hz⟩ := exists_ne (0 :
    localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P))
  obtain ⟨q, hq⟩ := hsurj z
  obtain ⟨f, rfl⟩ := Submodule.Quotient.mk_surjective _ q
  refine ⟨(f : X.functionField), f.2, ?_, ?_⟩
  · -- a section whose class is nonzero cannot be `0`
    intro hf0
    apply hz
    rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply]
    rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
      Submodule.coe_inclusion, mem_orderGeSub, hf0]
    exact (orderGe _ _).zero_mem
  · -- the two inequalities
    have hlow : -(show X.PrimeDivisor →₀ ℤ from D) P ≤
        Scheme.RationalMap.order P (f : X.functionField) := by
      rcases eq_or_ne (f : X.functionField) 0 with hf0 | hf0
      · exact absurd hf0 (by
          intro h
          apply hz
          rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply,
            Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
            Submodule.coe_inclusion, mem_orderGeSub, h]
          exact (orderGe _ _).zero_mem)
      exact (mem_sectionOfDivisor_of_ne_zero hf0).mp f.2 P
        (TopologicalSpace.Opens.mem_top P.point)
    have hhigh : Scheme.RationalMap.order P (f : X.functionField) <
        -(show X.PrimeDivisor →₀ ℤ from D) P + 1 := by
      by_contra hge
      apply hz
      rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply,
        Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
        Submodule.coe_inclusion, mem_orderGeSub]
      refine Or.inr ?_
      rw [sub_pointDivisor_apply_self]
      omega
    omega

/-- **Global generation at `P` from the two vanishings** — `evalMap_surjective`
composed with `generatedAt_of_evalMap_surjective`. -/
theorem generatedAt_of_vanishing
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P)))
    [Module.Finite k (sectionSub k ⊤ D)]
    [Module.Finite k (localStepTgt k P 1)] :
    GeneratedAt k D P :=
  generatedAt_of_evalMap_surjective k D P
    (evalMap_surjective k U₀ U₁ hledger D P hD hDP)

end GeneratedAt

end Adelic
end AlgebraicGeometry
