/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.RiemannRoch.Adelic.ClassInvariance

/-!
# Adelic Riemann–Roch — the residue-weighted degree and the section-drop bounds

This file supplies two further legs of the campaign's cluster P
(`informal/pic-representability-campaign.md`, P3/P4):

* the **residue-weighted (adelic) degree** `deg_k D = Σ_P D(P)·[κ(P):k]`, which is
  the degree the χ-ledger actually telescopes to (the geometric
  `Scheme.WeilDivisor.degree` is its specialisation at residue degree one, i.e.
  over an algebraically closed base field);
* the **section-drop bounds** `ℓ(D) ≤ ℓ(D + P) ≤ ℓ(D) + [κ(P):k]`, and their
  telescoped form `ℓ(D) ≤ ℓ(0) + deg_k D` for effective `D`.

The drop bounds are **unconditional** — they need neither the ledger's
connecting/surjectivity data nor the strong-approximation input, only the
finite-dimensionality instances.  The `≤` direction of the one-point step is
`localStep_finrank_le` (node N14, already landed) read through the rank–nullity
identity `finrank_localStepDom`; that is precisely the observation that the
*upper* bound of the χ-ledger does not need the residue map to be onto.

## Statements whose ledger input is explicit

The results that genuinely need the closed ledger `χ(D) = χ(0) + deg_k D` take it
as an explicit hypothesis `hledger`, in the same style as the existing
`Adelic.riemann_inequality`.  Nothing here introduces a new gate class, and no
statement is left as a `sorry`.  Under that hypothesis this file derives:

* `degK_principal_eq_zero` — **principal divisors have residue-weighted degree
  zero**, from the class-invariance of `χ` (`ClassInvariance.lean`).  This is the
  adelic form of the open geometric leaf
  `Scheme.WeilDivisor.principal_degree_zero`; see §4 for exactly what separates
  the two.
* `ell_eq_zero_of_degK_neg` — `deg_k D < 0 ⟹ ℓ(D) = 0` (campaign P4(a)).
* `degK_add_chi_zero_le_ell` — the Riemann inequality in closed weighted form.

## What is NOT proved here (read this before consuming)

Three distinct gaps in the vanishing story are kept apart deliberately:

1. **Single-field bounded vanishing** — `∃ b, ∀ D, b ≤ deg_k D → h¹(D) = 0`, for
   one fixed base field `k`.  Not proved here and not derivable from the ledger
   alone: it needs a base vanishing `h¹(𝒪(n₀·x₀)) = 0` plus surjectivity of
   `Ȟ¹(D) → Ȟ¹(D')` (the "peel an effective divisor" step).  The sibling project
   proves its analogue (`AJCR RiemannRoch/UniformVanishing.lean`) from an
   FLV-class machine that has no AJC counterpart.
2. **Extension uniformity** — the *same* `b` for every field extension `κ/k`.
   Strictly more than (1): it needs flat base change of the bound along
   `k → κ`.  Nothing in this file quantifies over extensions.
3. **Global generation** — `𝒪(D)` generated by global sections above the bound.
   Strictly more than (1) and (2): it needs `h¹(D − x) = 0` at every closed
   point, i.e. the bound raised by the maximum residue degree.  Not addressed
   here at all.

## Provenance

The residue-weighted degree, the drop bound and the `deg < 0 ⟹ ℓ = 0` corollary
are **rederived in the AJC adelic abstractions**; they are not ports.  The
sibling `AJCR RiemannRoch/SectionBound.lean` / `Degree.lean` prove related
statements on the `CurveDivisor`/`divisorSheaf` substrate, whose names do not
exist in this project.  The argument reused from AJCR is the χ-transport step of
`deg_divOf`; its AJC counterpart is `chi_eq_of_principal_shift`.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits IsDedekindDomain
open scoped WithZero

namespace AlgebraicGeometry
namespace Adelic

/-! ## §1. The residue-weighted (adelic) degree -/

section DegK

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **The residue-weighted degree homomorphism `deg_k : Div(X) →+ ℤ`.**
`deg_k D = Σ_P D(P)·[κ(P):k]`, the degree the χ-ledger telescopes to
(`chi_telescope_list`).  Bundled as an `AddMonoidHom` through
`Finsupp.liftAddHom`, exactly as the unweighted `Scheme.WeilDivisor.degree_hom`
is, so additivity, `deg_k 0 = 0` and `deg_k (-D) = -deg_k D` come for free.

Over an algebraically closed base field every closed point of a smooth curve has
`[κ(P):k] = 1` and this is the geometric degree; over a general `k` the weighting
is what makes the degree a linear-equivalence invariant. -/
noncomputable def degKHom : X.WeilDivisor →+ ℤ :=
  Finsupp.liftAddHom (fun P : X.PrimeDivisor =>
    (AddMonoidHom.mulRight ((residueDeg k P : ℤ)) : ℤ →+ ℤ))

/-- **The residue-weighted degree of a Weil divisor.** -/
noncomputable def degK (D : X.WeilDivisor) : ℤ := degKHom k D

theorem degK_eq_sum (D : X.WeilDivisor) :
    degK k D = (show X.PrimeDivisor →₀ ℤ from D).sum
      (fun P n => n * (residueDeg k P : ℤ)) :=
  Finsupp.liftAddHom_apply (α := X.PrimeDivisor) (M := ℤ) (N := ℤ) _ _

@[simp] theorem degK_zero : degK k (0 : X.WeilDivisor) = 0 := map_zero _

theorem degK_add (D D' : X.WeilDivisor) :
    degK k (D + D') = degK k D + degK k D' := map_add _ _ _

@[simp] theorem degK_neg (D : X.WeilDivisor) : degK k (-D) = -degK k D :=
  map_neg _ _

theorem degK_sub (D D' : X.WeilDivisor) :
    degK k (D - D') = degK k D - degK k D' := map_sub _ _ _

/-- **The one-point divisor has weighted degree the residue degree.** -/
@[simp] theorem degK_pointDivisor (P : X.PrimeDivisor) :
    degK k (pointDivisor P : X.WeilDivisor) = (residueDeg k P : ℤ) := by
  rw [degK_eq_sum, pointDivisor]
  exact (Finsupp.sum_single_index (by simp)).trans (one_mul _)

/-- **The weighted degree of a list-effective divisor is the sum of the residue
degrees** — the numerical companion of `chi_telescope_list`. -/
theorem degK_divisorOfList (L : List X.PrimeDivisor) :
    degK k (divisorOfList L : X.WeilDivisor) = ((L.map (residueDeg k)).sum : ℤ) := by
  induction L with
  | nil => simp [divisorOfList]
  | cons P L ih =>
    rw [divisorOfList, degK_add, degK_pointDivisor, ih, List.map_cons, List.sum_cons]
    push_cast
    ring

/-- **An effective divisor has nonnegative weighted degree.**  Each summand
`D(P)·[κ(P):k]` is a product of nonnegative integers. -/
theorem degK_nonneg_of_nonneg {D : X.WeilDivisor}
    (hD : ∀ P : X.PrimeDivisor, 0 ≤ (show X.PrimeDivisor →₀ ℤ from D) P) :
    0 ≤ degK k D := by
  rw [degK_eq_sum, Finsupp.sum]
  exact Finset.sum_nonneg fun P _ =>
    mul_nonneg (hD P) (Int.natCast_nonneg _)

end DegK

/-! ## §2. The section-drop bounds (unconditional)

For a one-point twist `D' = D + P` the local step space
`Γ(⊤,𝒪(D'))/Γ(⊤,𝒪(D))` has dimension `ℓ(D') − ℓ(D)` (rank–nullity,
`finrank_localStepDom`) and dimension at most `[κ(P):k]` (node N14,
`localStep_finrank_le` applied at `U = ⊤`).  Both facts are already in the
project; combining them gives the classical section-drop sandwich
`ℓ(D) ≤ ℓ(D + P) ≤ ℓ(D) + [κ(P):k]` with **no** ledger exactness hypothesis and
**no** strong-approximation input — those are needed only for the `h¹` half of the
ledger, not for the `ℓ` half. -/

section Drops

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **`ℓ` is monotone in the divisor.**  `D ≤ D'` pointwise gives
`Γ(⊤,𝒪(D)) ⊆ Γ(⊤,𝒪(D'))`, hence `ℓ(D) ≤ ℓ(D')`. -/
theorem ell_mono {D D' : X.WeilDivisor}
    (hDD' : ∀ P : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D) P ≤
      (show X.PrimeDivisor →₀ ℤ from D') P)
    [Module.Finite k (sectionSub k ⊤ D')] :
    ell k D ≤ ell k D' :=
  Submodule.finrank_mono (sectionSub_mono k ⊤ hDD')

/-- **The one-point section-drop bound (unconditional).**  For a one-point twist
`D' = D + P`,
`ℓ(D) ≤ ℓ(D') ≤ ℓ(D) + [κ(P):k]`.

The upper bound is node N14 (`localStep_finrank_le` at `U = ⊤`) read through
rank–nullity (`finrank_localStepDom`); the lower bound is `ell_mono`.  Neither
half consumes the ledger's connecting/surjectivity data. -/
theorem ell_le_ell_add_residueDeg {D D' : X.WeilDivisor} {P : X.PrimeDivisor}
    (hstep : (show X.PrimeDivisor →₀ ℤ from D') P =
      (show X.PrimeDivisor →₀ ℤ from D) P + 1)
    (hle : ∀ Q : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D) Q ≤
      (show X.PrimeDivisor →₀ ℤ from D') Q)
    (hoff : ∀ Q : X.PrimeDivisor, Q ≠ P →
      (show X.PrimeDivisor →₀ ℤ from D) Q = (show X.PrimeDivisor →₀ ℤ from D') Q)
    [Module.Finite k (sectionSub k ⊤ D')]
    [Module.Finite k (localStepTgt k P 1)] :
    ell k D ≤ ell k D' ∧ (ell k D' : ℤ) ≤ ell k D + residueDeg k P := by
  refine ⟨ell_mono k hle, ?_⟩
  have hrn := finrank_localStepDom k ⊤ (sectionSub_mono k ⊤ hle)
  have hN14 := localStep_finrank_le k (TopologicalSpace.Opens.mem_top P.point)
    hstep hle hoff
  have hcast : (Module.finrank k (localStepDom k ⊤ D D') : ℤ) ≤ (residueDeg k P : ℤ) := by
    exact_mod_cast hN14
  simp only [ell] at *
  omega

/-- **The one-point drop bound in `pointDivisor` spelling.**  For the concrete
twist `D' = 1·P + D` the three coordinate hypotheses of
`ell_le_ell_add_residueDeg` are discharged by the `pointDivisor` calculus of the
χ-ledger, leaving the clean statement
`ℓ(D) ≤ ℓ(P + D) ≤ ℓ(D) + [κ(P):k]`. -/
theorem ell_add_pointDivisor_le (D : X.WeilDivisor) (P : X.PrimeDivisor)
    [Module.Finite k (sectionSub k ⊤ (pointDivisor P + D))]
    [Module.Finite k (localStepTgt k P 1)] :
    ell k D ≤ ell k (pointDivisor P + D) ∧
      (ell k (pointDivisor P + D) : ℤ) ≤ ell k D + residueDeg k P :=
  ell_le_ell_add_residueDeg k (add_pointDivisor_apply_self D P)
    (le_add_pointDivisor D P)
    (fun _ hQ => (add_pointDivisor_apply_of_ne D hQ).symm)

end Drops

/-! ## §3. Consequences of the closed ledger

The **closed ledger** is the identity `χ(D) = χ(0) + deg_k D` for every Weil
divisor `D`.  In this project it is not a theorem: `chi_telescope_list` proves it
for *effective* divisors from a per-step hypothesis which is one application of
`chi_add_eq_residueDeg`, and that in turn consumes the ledger's
connecting/surjectivity data plus the strong-approximation input `hsurj`.  So the
statements below take the closed ledger as an explicit hypothesis, spelled
exactly as it will be discharged:

`hledger : ∀ D, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D`.

That is an honest hypothesis, not a gate class and not a `sorry`: each theorem
here says "given the ledger, this follows", and the reader can see what is
missing. -/

section Ledger

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **The Riemann inequality in closed weighted form.**  Given the closed ledger,
`deg_k D + χ(0) ≤ ℓ(D)` for every `D` — the `h¹ ≥ 0` half applied to the
telescoped Euler characteristic.  (This is `Adelic.riemann_inequality` with its
`htel` hypothesis supplied from the ledger and the degree pinned to the
residue-weighted `deg_k`.) -/
theorem degK_add_chi_zero_le_ell
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D : X.WeilDivisor) :
    degK k D + chi k U₀ U₁ 0 ≤ (ell k D : ℤ) :=
  riemann_inequality k U₀ U₁ (hledger D)

end Ledger

section LedgerNoetherian

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **`deg_k D < 0 ⟹ ℓ(D) = 0`** (campaign P4(a)).  Given the closed ledger: a
nonzero `f ∈ L(D)` would make `D` linearly equivalent to an effective divisor
`E = D + div f` (`exists_effective_linearEquiv_of_ne_zero_mem`); `χ` is a
class invariant (`chi_eq_of_linearEquivalence`), so the ledger forces
`deg_k E = deg_k D < 0`, contradicting `deg_k E ≥ 0` for effective `E`
(`degK_nonneg_of_nonneg`).

Note the shape: the hypothesis is on `deg_k`, the *weighted* degree, and the
argument runs entirely through the class-invariance of `χ` — no vanishing input,
no duality. -/
theorem ell_eq_zero_of_degK_neg
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {D : X.WeilDivisor} (hdeg : degK k D < 0)
    [Module.Finite k (sectionSub k ⊤ D)] :
    ell k D = 0 := by
  by_contra hne
  -- a nonzero section exists
  obtain ⟨f, hfmem, hfne⟩ : ∃ f : X.functionField, f ∈ sectionSub k ⊤ D ∧ f ≠ 0 := by
    by_contra hno
    have hbot : sectionSub k ⊤ D = ⊥ := by
      apply le_antisymm _ bot_le
      intro x hx
      rcases eq_or_ne x 0 with rfl | hx0
      · exact Submodule.zero_mem _
      · exact absurd ⟨x, hx, hx0⟩ hno
    rw [ell, hbot] at hne
    simp at hne
  obtain ⟨E, hEnonneg, hEclass⟩ :=
    exists_effective_linearEquiv_of_ne_zero_mem hfne hfmem
  have hchi := chi_eq_of_linearEquivalence k U₀ U₁ hEclass
  rw [hledger E, hledger D] at hchi
  have : degK k E = degK k D := by omega
  have hEpos := degK_nonneg_of_nonneg k hEnonneg
  omega

/-- **Principal divisors have residue-weighted degree zero** — the adelic
counterpart of the geometric statement `Scheme.WeilDivisor.principal_degree_zero`.

Given the closed ledger, this is a two-line consequence of the class-invariance of
`χ` proved in `ClassInvariance.lean`: `0 − div g` is in the class of `0`, so
`χ(0 − div g) = χ(0)`, and the ledger reads off
`deg_k (0 − div g) = 0`, i.e. `deg_k (div g) = 0`.

This is the *weighted* statement.  It does **not** close the open geometric leaf
`principal_degree_zero`, which asserts the same for the unweighted degree
`Σ_P ord_P g`; see §4. -/
theorem degK_principal_eq_zero
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {g : X.functionField} (hg : g ≠ 0) :
    degK k (Scheme.WeilDivisor.principal g hg) = 0 := by
  have hchi := chi_eq_of_principal_shift k U₀ U₁ (0 : X.WeilDivisor) hg
  rw [hledger ((0 : X.WeilDivisor) - Scheme.WeilDivisor.principal g hg),
    hledger (0 : X.WeilDivisor), degK_sub, degK_zero] at hchi
  omega

/-- **`deg_k` descends to linear-equivalence classes.**  Given the closed ledger,
linearly equivalent divisors have equal weighted degree — the well-definedness
statement the Picard route consumes when it needs "the degree of a class". -/
theorem degK_eq_of_linearEquivalence
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {D D' : X.WeilDivisor} (h : Scheme.WeilDivisor.LinearEquivalence D D') :
    degK k D = degK k D' := by
  have hchi := chi_eq_of_linearEquivalence k U₀ U₁ h
  rw [hledger D, hledger D'] at hchi
  omega

end LedgerNoetherian

/-! ## §4. `degK_principal_eq_zero` versus the geometric `principal_degree_zero`

`degK_principal_eq_zero` above and the open leaf
`Scheme.WeilDivisor.principal_degree_zero` are **different statements**, and the
first does not imply the second.  Recorded here because the difference is easy to
misread as a formality.

* `degK_principal_eq_zero` concerns `deg_k (div g) = Σ_P ord_P(g)·[κ(P):k]`.  Its
  proof is the χ-transport of `ClassInvariance.lean` plus the closed ledger, and
  it is stated over an **arbitrary** base field of constants `k`.
* `principal_degree_zero` concerns the **unweighted** `Σ_P ord_P(g)`, and is
  stated on a smooth proper curve over an algebraically **closed** `k̄` with no
  field of constants in sight and no ledger hypothesis.

Over `k̄` the two degrees coincide because every closed point of a smooth curve has
residue field `k̄`, i.e. `[κ(P):k̄] = 1`.  Bridging them therefore requires
**exactly one** missing ingredient, which is neither the ledger nor
class-invariance:

> `residueDeg k̄ P = 1` for every prime divisor `P` of a smooth proper curve over
> an algebraically closed `k̄`.

That is a statement about residue fields of closed points (`κ(P)` is a finite
extension of `k̄`, hence `k̄`), plus the instances placing the geometric
hypotheses of `principal_degree_zero` in the shape the adelic lane needs: an
`Algebra k̄ K(C)` structure with `IsConstantField k̄ C.left` (available —
`Adelic/GateInstances.lean`), the finiteness instances, a 2-affine cover, and the
closed ledger for that cover.

So the honest statement of where the geometric leaf stands is: it is reducible to
the closed ledger plus residue-degree-one, **not** open for lack of the divisor
theory.  The Hartshorne II.6.10 route sketched in its docstring (build
`φ : C → ℙ¹` from `g` and use multiplicativity of degree under finite pullback) is
a *different*, heavier proof; the ledger route above is the cheaper one and is the
route the campaign's P3 milestone anticipated ("byproduct: closes the input to the
`WeilDivisor.lean` sorry").  The `sorry` is deliberately left in place rather than
replaced by a chain that would silently import the ledger hypothesis into a
theorem whose statement does not mention it. -/

end Adelic
end AlgebraicGeometry
