/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivRepAffChallenge
import AlgebraicJacobian.Picard.DivRankOneOpen
import AlgebraicJacobian.Picard.Pic0EndgameContract
import AlgebraicJacobian.Picard.Pic0HighDegreeRouteGuard
import AlgebraicJacobian.Picard.Pic0RankOneLocus
import AlgebraicJacobian.Picard.Pic0RankOneLocalDivisor
import AlgebraicJacobian.Picard.Pic0RankOneEvaluationZeroLocus
import AlgebraicJacobian.Picard.Pic0RankOneFibrePresentedProducerAffineEvaluation
import AlgebraicJacobian.Picard.Pic0RankOneFamilyCertificates
import AlgebraicJacobian.Picard.Pic0RankOneNativePresentation
import AlgebraicJacobian.Picard.Pic0RankOneNativePresentationOfLocal
import AlgebraicJacobian.Picard.Pic0RankOneFibrePresentedProducer
import AlgebraicJacobian.Picard.Pic0RankOneFibrePresentedProducerFiniteGlue
import AlgebraicJacobian.Picard.Pic0RankOneTranslatedCoverPicZero
import AlgebraicJacobian.Picard.Pic0RankOneTranslatedCoverMembership

/-!
# Narrow root for the AJCR-first Picard strategy

This root deliberately imports only the current route modules and contracts. Every later
contract endpoint must be checked here before it receives critical-path credit.

The tied local rank-one presentation, its canonical evaluation map, datum-side local-away
divisor equations, and the pullback-stable presentation locus are present. The conditional
`DivRankOneOpenData` representer and its open-immersion/base-change consumers are rooted. The
native evaluation section and the tied datum section have the same restriction-vanishing
predicate on every open, without a Noetherian hypothesis; their piece coordinates and principal
piece ideals agree, and those native-coordinate ideals commute with arbitrary affine
coefficient extension.

The native rank-one route now closes from certificates to public membership on the field fibre.
`RankOneFamilyCertificates.ofActualDatum` produces all four family certificates from a single
per-residue-field H1 witness plus a fibre class-degree law, with rank one computed
Noetherian-freely by `rankAtStalk_hModule_zero_eq_one_of_actualPairH1`. Arbitrary-cartesian
native base change is internalized by `isIso_canonicalBaseChangeMap_nativeModule`, so
`ofCertificatesWithNativeBaseChange` and `ofLocalPresentation` build native presentations with
no extra base-change certificate. Consequently `mem_picRankOneOpen_of_isSplitWitness` places
every split genus-degree field class in `PicRankOneOpen`, and the Pic0 separably closed
translated-cover feeder lands its translated layer element in the public locus:
`exists_sepClosedTranslated_mem_picRankOneOpen` is the phase-5 membership endpoint.

On the divisor side, the tied local presentation's finite principal-open evaluation divisors
glue: `exists_glued_rankOne_away_divisor_with_abel_evaluation` produces a `DivFamZarAff` over
the Noetherian etale carrier with the global Abel and relative-Picard identities, resting on
`baseOpenRankOneDivisor_awayMul_compat`. The big-site consumer scaffold reduces
`PicRankOneOpen.IsOpen` to one canonical evaluation-divisor classifier and per-test pullback
squares: `picRankOneOpen_isOpen_of_evaluationDivisorPullbackFamilies`. Still missing, and NOT
replaced here by axioms or local hypotheses: an inhabitant of `PicRankOneEvaluationDivisorData`
(the canonical global divisor / Abel section), the Abel isomorphism (the `AbelInverse`
uniqueness obligation and `evaluationIso` remain hypothetical), `PicRankOneOpen.IsOpen` itself,
the descent of the glued family divisor from the etale carrier to the arbitrary affine base,
and the later representability/descent/`JacobianData` endpoints.
-/

#check AlgebraicGeometry.divFunctorAff_representableBy_at
#check AlgebraicGeometry.divFunctorAff_genus_representableBy
#check AlgebraicGeometry.divFunctorAff_admissible_representableBy
#check AlgebraicGeometry.relCurve.isIntegral
#check AlgebraicGeometry.abelDivAffTrans
#check AlgebraicGeometry.abelDivAffSigma
#check AlgebraicGeometry.abelDivAffGenusSigma
#check AlgebraicGeometry.Scheme.toModuleKSheafOfModules
#check AlgebraicGeometry.canonicalBaseChangeMap
#check AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#check AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#check AlgebraicGeometry.PicRankOneLocalPresentation
#check AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseChangeRankOneCertificates
#check AlgebraicGeometry.RankOneFamilyCertificates.sectionsMap_tower
#check AlgebraicGeometry.RankOneFamilyCertificates.h0BaseChange_tower
#check AlgebraicGeometry.BasicOpenCocycleDatum.sectionsMap_tower
#check AlgebraicGeometry.BasicOpenCocycleDatum.sectionsMapTop_tower
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_tower
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_mul_eq
#check AlgebraicGeometry.PicRankOneNativePresentation.ofCertificates
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#check Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#check Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.sectionLocalEquationsOfDatumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.moduleSectionsEquiv
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict_eq_zero_iff
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLiftOfH0
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0_eq_moduleSectionsEquiv
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLift_restrict_eq_zero_iff
#check AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionLocalEquationsOfDatumSectionBaseChange_divEq_of_unit
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange_of_representation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#check AlgebraicGeometry.PicRankOneOpen
#check AlgebraicGeometry.PicRankOneOpen.IsOpen
#check AlgebraicGeometry.DivRankOneOpenData
#check AlgebraicGeometry.divRankOneOpenData_of_picRankOneOpen_isOpen
#check AlgebraicGeometry.DivRankOneOpen
#check AlgebraicGeometry.divRankOneOpen_isOpenImmersion
#check AlgebraicGeometry.divRankOneOpen_mem_iff
#check AlgebraicGeometry.divRankOneOpen_baseChange_mem
#check AlgebraicGeometry.PicRankOneNativePresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.toLocalPresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_restrict_eq_zero_iff
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceCoordinate
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceCoordinate_sectionsMapTop
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceIdeal_sectionsMapTop
#check
  AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_nativePieceIdeal_eq_componentIdeal
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSectionsEquiv
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSheafIso
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModule_isLineBundle
#check AlgebraicGeometry.mem_picRankOneOpen_of_nativePresentations
#check AlgebraicGeometry.exists_sepClosedTranslatedRankOneLayer_pic0
#check AlgebraicGeometry.SepClosedTranslatedDropResult.translator_classDeg_of_pic0
#check AlgebraicGeometry.SepClosedTranslatedDropResult.baseSubtraction_compatibility
#check AlgebraicGeometry.divRankOnePresentationPreimageRepresenter
#check AlgebraicGeometry.rankOneAbelRepresented
#check AlgebraicGeometry.not_injective_abelSigmaChart_of_divFamZar
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#check AlgebraicGeometry.not_injective_abelSigmaChartAff_of_divFamZarAff
#check AlgebraicGeometry.not_injective_chartValueAff_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_not_injective_chartValueAff
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree

#print axioms AlgebraicGeometry.divFunctorAff_representableBy_at
#print axioms AlgebraicGeometry.divFunctorAff_genus_representableBy
#print axioms AlgebraicGeometry.divFunctorAff_admissible_representableBy
#print axioms AlgebraicGeometry.abelDivAffGenusSigma
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseChangeRankOneCertificates
#print axioms AlgebraicGeometry.RankOneFamilyCertificates.sectionsMap_tower
#print axioms AlgebraicGeometry.RankOneFamilyCertificates.h0BaseChange_tower
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.sectionsMap_tower
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.sectionsMapTop_tower
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_tower
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_mul_eq
#print axioms AlgebraicGeometry.PicRankOneNativePresentation.ofCertificates
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#print axioms AlgebraicGeometry.divRankOneOpenData_of_picRankOneOpen_isOpen
#print axioms AlgebraicGeometry.divRankOneOpen_isOpenImmersion
#print axioms AlgebraicGeometry.divRankOneOpen_baseChange_mem
#print axioms AlgebraicGeometry.PicRankOneNativePresentation.toLocalPresentation
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSheafIso
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModule_isLineBundle
#print axioms AlgebraicGeometry.mem_picRankOneOpen_of_nativePresentations
#print axioms AlgebraicGeometry.exists_sepClosedTranslatedRankOneLayer_pic0
#print axioms AlgebraicGeometry.SepClosedTranslatedDropResult.translator_classDeg_of_pic0
#print axioms AlgebraicGeometry.SepClosedTranslatedDropResult.baseSubtraction_compatibility
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict_eq_zero_iff
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0_eq_moduleSectionsEquiv
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLift_restrict_eq_zero_iff
#print axioms
  AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_restrict_eq_zero_iff
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceCoordinate
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceCoordinate_eq_component
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceCoordinate_sectionsMapTop
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativePieceIdeal_sectionsMapTop
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModuleKSectionsEquiv_symm_apply
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModuleKSheafIso_inv_app
#print axioms
  AlgebraicGeometry.PicRankOneNativePresentation.moduleSectionsEquiv_nativePieceCoordinate_eq_component
#print axioms
  AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_nativePieceCoordinate_eq_component
#print axioms
  AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_nativePieceIdeal_eq_componentIdeal
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#print axioms Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#print axioms Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
namespace AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms sectionLocalEquationsOfDatumSectionBaseChange_picClass
end AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
namespace AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms sectionLocalEquationsOfDatumSectionBaseChange_divEq_of_unit
end AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange_of_representation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.existsUnique_unit_tensorAway_rankOne_generators
#print axioms AlgebraicGeometry.rankOneAbelRepresented
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree

-- Native datum layer (Pic0RankOneNativePresentationDatum.lean)
#check AlgebraicGeometry.PicRankOneNativeDatum
#check AlgebraicGeometry.PicRankOneNativeDatum.nonempty
#check AlgebraicGeometry.PicRankOneNativeDatum.classDeg_baseChange
#check AlgebraicGeometry.PicRankOneNativeDatum.residueH1Witness_of_isSplitWitness
-- Native datum from a field pullback (Pic0RankOneNativePresentationField.lean)
#check AlgebraicGeometry.PicRankOneNativeDatum.residueH1Witness_of_fieldPullback
#check AlgebraicGeometry.isSplitWitness_map_overSpecMap_of_algHom
-- Arbitrary-cartesian native base change (Pic0RankOneNativeBaseChangeCartesian.lean)
#check AlgebraicGeometry.BasicOpenCocycleDatum.isIso_canonicalBaseChangeMap_nativeModule
#check AlgebraicGeometry.PicRankOneNativePresentation.ofCertificatesWithNativeBaseChange
-- Four-certificate producer from the actual datum (Cohomology/RankOneFamilyCertificatesActualDatum.lean)
#check AlgebraicGeometry.BasicOpenCocycleDatum.ResidueH1Witness
#check AlgebraicGeometry.BasicOpenCocycleDatum.FibreClassDegree
#check AlgebraicGeometry.RankOneFamilyCertificates.ofActualDatum
-- Rank one without a Noetherian hypothesis (Cohomology/RankOneFamilyCertificatesActualDatumRank.lean)
#check AlgebraicGeometry.BasicOpenCocycleDatum.rankAtStalk_hModule_zero_eq_one_of_actualPairH1
-- Datum-to-certificates-to-native-presentation wrappers (Pic0RankOneFamilyCertificatesActualDatum.lean)
#check AlgebraicGeometry.PicRankOneNativeDatum.familyCertificates
#check AlgebraicGeometry.PicRankOneNativeDatum.familyCertificatesBaseChange
#check AlgebraicGeometry.PicRankOneNativePresentation.ofNativeDatum
-- Local-to-native presentation converter (Pic0RankOneNativePresentationOfLocal.lean)
#check AlgebraicGeometry.PicRankOneNativePresentation.ofLocalPresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.nonempty_of_localPresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.nonempty_of_localPresentations
-- Split field class gives membership in PicRankOneOpen (Pic0RankOneNativePresentationSplit.lean)
#check AlgebraicGeometry.exists_algHom_eq_of_overSpec_hom_of_commRing
#check AlgebraicGeometry.PicRankOneNativeDatum.toNativePresentation_of_residueH1Witness
#check AlgebraicGeometry.PicRankOneNativePresentation.nonempty_of_fieldPullback
#check AlgebraicGeometry.mem_picRankOneOpen_of_isSplitWitness
-- Datum-side away-divisor naturality (Pic0RankOneFibrePresentedProducerAwayNaturality.lean)
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_mapAlgHom_mul_left
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_mapAlgHom_mul_right
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_awayMul_compat
-- Section/divisor equality helpers (Pic0RankOneFibrePresentedProducerSectionDivEq.lean)
#check AlgebraicGeometry.BasicOpenCocycleDatum.sectionLocalEquations_divEq_of_same_section
#check
  AlgebraicGeometry.BasicOpenCocycleDatum.pullback_sectionLocalEquationsOfFibrewiseRegular_divEq_sectionsMapTop
-- Finite gluing of away-divisors to a family divisor (Pic0RankOneFibrePresentedProducerFiniteGlue.lean)
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_glued_rankOne_away_divisor_with_abel_evaluation
-- Big-site consumer scaffold (Pic0RankOneFibrePresentedProducer.lean)
#check AlgebraicGeometry.rankOneAbelSigma
#check AlgebraicGeometry.rankOneDivisorToAmbient
#check AlgebraicGeometry.PicRankOneEvaluationDivisorData
#check AlgebraicGeometry.PicRankOneFibrePresentationInput
#check AlgebraicGeometry.PicRankOneFibrePresentationInput.EvaluationDivisorPullback
#check AlgebraicGeometry.PicRankOneFibrePresentationInput.toFibrePresented_of_evaluationDivisorPullback
#check
  AlgebraicGeometry.PicRankOneFibrePresentationInput.picRankOneOpen_isOpen_of_evaluationDivisorPullbackFamilies
-- Phase-5 translated-cover membership endpoint (Pic0RankOneTranslatedCoverMembership.lean)
#check AlgebraicGeometry.exists_sepClosedTranslated_mem_picRankOneOpen

#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.isIso_canonicalBaseChangeMap_nativeModule
#print axioms AlgebraicGeometry.PicRankOneNativePresentation.ofCertificatesWithNativeBaseChange
#print axioms AlgebraicGeometry.RankOneFamilyCertificates.ofActualDatum
#print axioms
  AlgebraicGeometry.BasicOpenCocycleDatum.rankAtStalk_hModule_zero_eq_one_of_actualPairH1
#print axioms AlgebraicGeometry.PicRankOneNativePresentation.nonempty_of_localPresentations
#print axioms AlgebraicGeometry.mem_picRankOneOpen_of_isSplitWitness
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_awayMul_compat
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_glued_rankOne_away_divisor_with_abel_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneFibrePresentationInput.picRankOneOpen_isOpen_of_evaluationDivisorPullbackFamilies
#print axioms AlgebraicGeometry.exists_sepClosedTranslated_mem_picRankOneOpen
