/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivRepAffChallenge
import AlgebraicJacobian.Picard.DivRankOneOpen
import AlgebraicJacobian.Picard.Pic0EndgameContract
import AlgebraicJacobian.Picard.Pic0HighDegreeRouteGuard
import AlgebraicJacobian.Picard.Pic0RankOneLocus
import AlgebraicJacobian.Picard.Pic0RankOneLocalDivisor
import AlgebraicJacobian.Picard.Pic0RankOneEvaluationZeroLocus
import AlgebraicJacobian.Picard.Pic0RankOneNativePresentation
import AlgebraicJacobian.Picard.Pic0RankOneTranslatedCoverPicZero

/-!
# Narrow root for the AJCR-first Picard strategy

This root deliberately imports only the current route modules and contracts. Every later
contract endpoint must be checked here before it receives critical-path credit.

The tied local rank-one presentation, its canonical evaluation map, datum-side local-away
divisor equations, and the pullback-stable presentation locus are present. The conditional
`DivRankOneOpenData` representer and its open-immersion/base-change consumers are rooted, but
the arbitrary-affine presentation producer needed to prove `PicRankOneOpen.IsOpen` is still
missing. The native evaluation section and the tied datum section now have the same restriction-
vanishing predicate on every open, without a Noetherian hypothesis. Identifying the resulting
intrinsic zero locus with the datum local equations and gluing it to a family divisor are still
missing. Unit rescaling of the section-cut equations is now coefficient-ring-uniform, and the
fixed-open `DivFamZarAff` equality consumes that theorem. Naturality under coefficient extension,
which is needed to compare two basic-open divisors on their overlap, and the resulting family-level
divisor producer are not claimed.

The Pic0-specialized separably closed translated-layer feeder is also rooted: it keeps the
translator degree and the exact subtraction compatibility tied to one result. It does not
supply membership in `PicRankOneOpen` or the translated-cover endpoint. The canonical divisor,
Abel isomorphism, separably closed cover, later representability/descent endpoints, and
`JacobianData` declarations do not yet exist. They are not replaced here by axioms or local
hypotheses.
-/

#check AlgebraicGeometry.divFunctorAff_representableBy_at
#check AlgebraicGeometry.divFunctorAff_genus_representableBy
#check AlgebraicGeometry.divFunctorAff_admissible_representableBy
#check AlgebraicGeometry.relCurve.isIntegral
#check AlgebraicGeometry.abelDivAffTrans
#check AlgebraicGeometry.abelDivAffSigma
#check AlgebraicGeometry.abelDivAffGenusSigma
#check AlgebraicGeometry.Scheme.toModuleKSheafOfModules
#check AlgebraicGeometry.canonicalBaseChangeMap
#check AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#check AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#check AlgebraicGeometry.PicRankOneLocalPresentation
#check AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseChangeRankOneCertificates
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#check Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#check Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.sectionLocalEquationsOfDatumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.moduleSectionsEquiv
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict_eq_zero_iff
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLiftOfH0
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0_eq_moduleSectionsEquiv
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLift_restrict_eq_zero_iff
#check AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionLocalEquationsOfDatumSectionBaseChange_divEq_of_unit
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange_of_representation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#check AlgebraicGeometry.PicRankOneOpen
#check AlgebraicGeometry.PicRankOneOpen.IsOpen
#check AlgebraicGeometry.DivRankOneOpenData
#check AlgebraicGeometry.divRankOneOpenData_of_picRankOneOpen_isOpen
#check AlgebraicGeometry.DivRankOneOpen
#check AlgebraicGeometry.divRankOneOpen_isOpenImmersion
#check AlgebraicGeometry.divRankOneOpen_mem_iff
#check AlgebraicGeometry.divRankOneOpen_baseChange_mem
#check AlgebraicGeometry.PicRankOneNativePresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.toLocalPresentation
#check AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_restrict_eq_zero_iff
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSectionsEquiv
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSheafIso
#check AlgebraicGeometry.BasicOpenCocycleDatum.nativeModule_isLineBundle
#check AlgebraicGeometry.mem_picRankOneOpen_of_nativePresentations
#check AlgebraicGeometry.exists_sepClosedTranslatedRankOneLayer_pic0
#check AlgebraicGeometry.SepClosedTranslatedDropResult.translator_classDeg_of_pic0
#check AlgebraicGeometry.SepClosedTranslatedDropResult.baseSubtraction_compatibility
#check AlgebraicGeometry.divRankOnePresentationPreimageRepresenter
#check AlgebraicGeometry.rankOneAbelRepresented
#check AlgebraicGeometry.not_injective_abelSigmaChart_of_divFamZar
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#check AlgebraicGeometry.not_injective_abelSigmaChartAff_of_divFamZarAff
#check AlgebraicGeometry.not_injective_chartValueAff_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_not_injective_chartValueAff
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree

#print axioms AlgebraicGeometry.divFunctorAff_representableBy_at
#print axioms AlgebraicGeometry.divFunctorAff_genus_representableBy
#print axioms AlgebraicGeometry.divFunctorAff_admissible_representableBy
#print axioms AlgebraicGeometry.abelDivAffGenusSigma
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseChangeRankOneCertificates
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#print axioms AlgebraicGeometry.divRankOneOpenData_of_picRankOneOpen_isOpen
#print axioms AlgebraicGeometry.divRankOneOpen_isOpenImmersion
#print axioms AlgebraicGeometry.divRankOneOpen_baseChange_mem
#print axioms AlgebraicGeometry.PicRankOneNativePresentation.toLocalPresentation
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModulePieceSheafIso
#print axioms AlgebraicGeometry.BasicOpenCocycleDatum.nativeModule_isLineBundle
#print axioms AlgebraicGeometry.mem_picRankOneOpen_of_nativePresentations
#print axioms AlgebraicGeometry.exists_sepClosedTranslatedRankOneLayer_pic0
#print axioms AlgebraicGeometry.SepClosedTranslatedDropResult.translator_classDeg_of_pic0
#print axioms AlgebraicGeometry.SepClosedTranslatedDropResult.baseSubtraction_compatibility
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_restrict_eq_zero_iff
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0_eq_moduleSectionsEquiv
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLift_restrict_eq_zero_iff
#print axioms
  AlgebraicGeometry.PicRankOneNativePresentation.evaluationLift_restrict_eq_zero_iff
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#print axioms Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#print axioms Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
namespace AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms sectionLocalEquationsOfDatumSectionBaseChange_picClass
end AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
namespace AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms sectionLocalEquationsOfDatumSectionBaseChange_divEq_of_unit
end AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange_of_representation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.existsUnique_unit_tensorAway_rankOne_generators
#print axioms AlgebraicGeometry.rankOneAbelRepresented
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree
