/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivRepAffChallenge
import AlgebraicJacobian.Picard.Pic0EndgameContract
import AlgebraicJacobian.Picard.Pic0HighDegreeRouteGuard
import AlgebraicJacobian.Picard.Pic0RankOneLocus
import AlgebraicJacobian.Picard.Pic0RankOneLocalDivisor

/-!
# Narrow root for the AJCR-first Picard strategy

This root deliberately imports only the current producers on the reviewed route. Every later
contract endpoint must be checked here before it receives critical-path credit.

The tied local rank-one presentation, its canonical evaluation map, datum-side local-away
divisor equations, and the pullback-stable presentation locus are present. The native
evaluation zero locus is not yet identified with those datum equations, and the locus is not
yet proved open or represented. Fixed-open unit-independence now has a canonical H0 linearity
bridge and a `DivFamZarAff` equality consumer, but no family-level divisor producer is claimed.
The canonical divisor, Abel isomorphism, separably closed cover, representability, descent, and
`JacobianData` declarations do not yet exist. They are not replaced here by axioms or local
hypotheses.
-/

#check AlgebraicGeometry.divFunctorAff_representableBy_at
#check AlgebraicGeometry.divFunctorAff_genus_representableBy
#check AlgebraicGeometry.divFunctorAff_admissible_representableBy
#check AlgebraicGeometry.relCurve.isIntegral
#check AlgebraicGeometry.abelDivAffTrans
#check AlgebraicGeometry.abelDivAffSigma
#check AlgebraicGeometry.abelDivAffGenusSigma
#check AlgebraicGeometry.Scheme.toModuleKSheafOfModules
#check AlgebraicGeometry.canonicalBaseChangeMap
#check AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#check AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#check AlgebraicGeometry.PicRankOneLocalPresentation
#check AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#check AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#check Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#check Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.sectionLocalEquationsOfDatumSectionBaseChange
#check AlgebraicGeometry.PicRankOneLocalPresentation.moduleSectionsEquiv
#check AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluationLiftOfH0
#check AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#check AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#check AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#check
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#check AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#check AlgebraicGeometry.PicRankOneOpen
#check AlgebraicGeometry.divRankOnePresentationPreimageRepresenter
#check AlgebraicGeometry.rankOneAbelRepresented
#check AlgebraicGeometry.not_injective_abelSigmaChart_of_divFamZar
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#check AlgebraicGeometry.not_injective_abelSigmaChartAff_of_divFamZarAff
#check AlgebraicGeometry.not_injective_chartValueAff_of_not_injective_chartValue
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_not_injective_chartValueAff
#check AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree

#print axioms AlgebraicGeometry.divFunctorAff_representableBy_at
#print axioms AlgebraicGeometry.divFunctorAff_genus_representableBy
#print axioms AlgebraicGeometry.divFunctorAff_admissible_representableBy
#print axioms AlgebraicGeometry.abelDivAffGenusSigma
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.h0BaseChange
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_pullback_counit
#print axioms AlgebraicGeometry.canonicalBaseChangeMap_counit_cancel
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.nativeBaseChangeIsoAffine
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIso_hom_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.evaluationSourceBaseChangeIsoAffine_hom_evaluation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.module_iso_inv_datumSection
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_one_tmul
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChangeLinearMap
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.datumSectionBaseChange_eq_smul_of_tensor_eq
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.tensorAwayGenerator_fibre_ne_zero
#print axioms Module.bijective_toSpanSingleton_of_forall_tmul_ne_zero
#print axioms Module.existsUnique_unit_smul_of_forall_tmul_ne_zero
namespace AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms sectionLocalEquationsOfDatumSectionBaseChange_picClass
end AlgebraicGeometry.PicRankOneLocalPresentation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.evaluation_evaluationLiftOfH0
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_evaluation_generator
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.sectionsMapTop_datumSectionBaseChange_away_ne_zero
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_fibrewiseRegular
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_classDeg
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq_of_unit
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenDatumSectionLocalEquations_divEq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_eq
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_picClass
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.baseOpenRankOneDivisor_abelAff
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_evaluation
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.exists_baseOpen_rankOne_divisor_with_abel_evaluation
#print axioms AlgebraicGeometry.PicRankOneLocalPresentation.datum_classDeg_baseChange
#print axioms
  AlgebraicGeometry.PicRankOneLocalPresentation.existsUnique_unit_tensorAway_rankOne_generators
#print axioms AlgebraicGeometry.rankOneAbelRepresented
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChart_of_genus_lt_degree
#print axioms AlgebraicGeometry.not_isOpenImmersion_abelSigmaChartAff_of_genus_lt_degree
