import AlgebraicJacobian.Picard.Pic0ChartSeamCollapse
open AlgebraicGeometry
#print axioms AlgebraicGeometry.isSheaf_yoneda_obj
#print axioms AlgebraicGeometry.chartSourceSheaf
#print axioms AlgebraicGeometry.chartSheafHom
#print axioms AlgebraicGeometry.isLocallySurjective_oneChart
#print axioms AlgebraicGeometry.chartIso_of_seam
#print axioms AlgebraicGeometry.seam_of_chartIso
#print axioms AlgebraicGeometry.representableBy_of_seam
#print axioms AlgebraicGeometry.exists_retraction_of_seam
#print axioms AlgebraicGeometry.eq_top_of_retraction_of_isDominant
#print axioms AlgebraicGeometry.eq_top_of_seam_of_isDominant
#print axioms AlgebraicGeometry.isDominant_opens_ι_of_irreducibleSpace
#print axioms AlgebraicGeometry.eq_top_of_seam_of_irreducible
#print axioms AlgebraicGeometry.chartIso_of_isChartUniv
#print axioms AlgebraicGeometry.injective_abelSigmaChart_of_seam_of_irreducible
#print axioms AlgebraicGeometry.exists_retraction_of_isChartUniv
#print axioms AlgebraicGeometry.Jacobian
